// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package database

import (
	"context"
	"database/sql"
)

const getDecoderParams = `-- name: GetDecoderParams :one
SELECT ext_trigger, trg_code_1, trg_code_2, read_pmts, read_sipms, read_trigger, read_fibers, split_trigger, no_db, discard, host, user, passwd, db_name, write_data, use_blosc, blosc_algorithm, compression_level, bit_shuffle FROM decoderParams LIMIT 1
`

func (q *Queries) GetDecoderParams(ctx context.Context) (Decoderparam, error) {
	row := q.db.QueryRowContext(ctx, getDecoderParams)
	var i Decoderparam
	err := row.Scan(
		&i.ExtTrigger,
		&i.TrgCode1,
		&i.TrgCode2,
		&i.ReadPmts,
		&i.ReadSipms,
		&i.ReadTrigger,
		&i.ReadFibers,
		&i.SplitTrigger,
		&i.NoDb,
		&i.Discard,
		&i.Host,
		&i.User,
		&i.Passwd,
		&i.DbName,
		&i.WriteData,
		&i.UseBlosc,
		&i.BloscAlgorithm,
		&i.CompressionLevel,
		&i.BitShuffle,
	)
	return i, err
}

const getDisabledEquipments = `-- name: GetDisabledEquipments :many
SELECT id, type, device_ip, host_ip, host_port, enabled, ldcid FROM equipments WHERE enabled = 0
`

func (q *Queries) GetDisabledEquipments(ctx context.Context) ([]Equipment, error) {
	rows, err := q.db.QueryContext(ctx, getDisabledEquipments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Equipment{}
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.DeviceIp,
			&i.HostIp,
			&i.HostPort,
			&i.Enabled,
			&i.Ldcid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDisabledGDCs = `-- name: GetDisabledGDCs :many
SELECT id, name, hostname, ip, port, grpc_port, prometheus_port, datapath, enabled, writeoutput, decode FROM gdcs WHERE enabled = 0
`

func (q *Queries) GetDisabledGDCs(ctx context.Context) ([]Gdc, error) {
	rows, err := q.db.QueryContext(ctx, getDisabledGDCs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gdc{}
	for rows.Next() {
		var i Gdc
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.Ip,
			&i.Port,
			&i.GrpcPort,
			&i.PrometheusPort,
			&i.Datapath,
			&i.Enabled,
			&i.Writeoutput,
			&i.Decode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDisabledLDCs = `-- name: GetDisabledLDCs :many
SELECT id, name, hostname, ip, grpc_port, prometheus_port, enabled FROM ldcs WHERE enabled = 0
`

func (q *Queries) GetDisabledLDCs(ctx context.Context) ([]Ldc, error) {
	rows, err := q.db.QueryContext(ctx, getDisabledLDCs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ldc{}
	for rows.Next() {
		var i Ldc
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.Ip,
			&i.GrpcPort,
			&i.PrometheusPort,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDuckParams = `-- name: GetDuckParams :one
SELECT filesize, experiment, packetsize, npacketsinbuffer, buffertimeout, equipmentdatach, receivech, datach, metricsch, tcpconnectionsch, decoderch, decoderworkers, writerch FROM duckParams LIMIT 1
`

func (q *Queries) GetDuckParams(ctx context.Context) (Duckparam, error) {
	row := q.db.QueryRowContext(ctx, getDuckParams)
	var i Duckparam
	err := row.Scan(
		&i.Filesize,
		&i.Experiment,
		&i.Packetsize,
		&i.Npacketsinbuffer,
		&i.Buffertimeout,
		&i.Equipmentdatach,
		&i.Receivech,
		&i.Datach,
		&i.Metricsch,
		&i.Tcpconnectionsch,
		&i.Decoderch,
		&i.Decoderworkers,
		&i.Writerch,
	)
	return i, err
}

const getGDCsWithoutWrite = `-- name: GetGDCsWithoutWrite :many
SELECT id, name, hostname, ip, port, grpc_port, prometheus_port, datapath, enabled, writeoutput, decode FROM gdcs WHERE writeOutput = 0
`

func (q *Queries) GetGDCsWithoutWrite(ctx context.Context) ([]Gdc, error) {
	rows, err := q.db.QueryContext(ctx, getGDCsWithoutWrite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gdc{}
	for rows.Next() {
		var i Gdc
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.Ip,
			&i.Port,
			&i.GrpcPort,
			&i.PrometheusPort,
			&i.Datapath,
			&i.Enabled,
			&i.Writeoutput,
			&i.Decode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestRun = `-- name: GetLatestRun :one
SELECT id FROM runs ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetLatestRun(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, getLatestRun)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getLatestRunWithTimestamp = `-- name: GetLatestRunWithTimestamp :one
SELECT id, start, stop FROM runs ORDER BY id DESC LIMIT 1
`

// Run management queries
func (q *Queries) GetLatestRunWithTimestamp(ctx context.Context) (Run, error) {
	row := q.db.QueryRowContext(ctx, getLatestRunWithTimestamp)
	var i Run
	err := row.Scan(&i.ID, &i.Start, &i.Stop)
	return i, err
}

const getRateByRun = `-- name: GetRateByRun :one
SELECT run FROM rates WHERE run = ?
`

// Rate management queries
func (q *Queries) GetRateByRun(ctx context.Context, run int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getRateByRun, run)
	err := row.Scan(&run)
	return run, err
}

const getTestDeviceParams = `-- name: GetTestDeviceParams :many
SELECT equipment_id, event_rate_ms, packets_per_event, packet_size, error_injection_rate, max_events FROM testDeviceParams
`

func (q *Queries) GetTestDeviceParams(ctx context.Context) ([]Testdeviceparam, error) {
	rows, err := q.db.QueryContext(ctx, getTestDeviceParams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Testdeviceparam{}
	for rows.Next() {
		var i Testdeviceparam
		if err := rows.Scan(
			&i.EquipmentID,
			&i.EventRateMs,
			&i.PacketsPerEvent,
			&i.PacketSize,
			&i.ErrorInjectionRate,
			&i.MaxEvents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopiParams = `-- name: GetTopiParams :one
SELECT id, enabled, daemon_url, api_token, rabbitmq_address, rabbitmq_port, rabbitmq_user, rabbitmq_password, rabbitmq_vhost, exchange_name, control_queue, selected_configuration FROM topiParams WHERE id = 1
`

func (q *Queries) GetTopiParams(ctx context.Context) (Topiparam, error) {
	row := q.db.QueryRowContext(ctx, getTopiParams)
	var i Topiparam
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.DaemonUrl,
		&i.ApiToken,
		&i.RabbitmqAddress,
		&i.RabbitmqPort,
		&i.RabbitmqUser,
		&i.RabbitmqPassword,
		&i.RabbitmqVhost,
		&i.ExchangeName,
		&i.ControlQueue,
		&i.SelectedConfiguration,
	)
	return i, err
}

const insertGDCBytes = `-- name: InsertGDCBytes :exec
INSERT INTO data (run, gdc_id, ldc_id, bytes) VALUES (?, ?, NULL, ?)
`

type InsertGDCBytesParams struct {
	Run   int32         `db:"run" json:"run"`
	GdcID sql.NullInt32 `db:"gdc_id" json:"gdc_id"`
	Bytes sql.NullInt64 `db:"bytes" json:"bytes"`
}

func (q *Queries) InsertGDCBytes(ctx context.Context, arg InsertGDCBytesParams) error {
	_, err := q.db.ExecContext(ctx, insertGDCBytes, arg.Run, arg.GdcID, arg.Bytes)
	return err
}

const insertGDCErrorCount = `-- name: InsertGDCErrorCount :exec
INSERT INTO errors (run, gdc_id, ldc_id, errors) VALUES (?, ?, NULL, ?)
`

type InsertGDCErrorCountParams struct {
	Run    int32         `db:"run" json:"run"`
	GdcID  sql.NullInt32 `db:"gdc_id" json:"gdc_id"`
	Errors sql.NullInt64 `db:"errors" json:"errors"`
}

func (q *Queries) InsertGDCErrorCount(ctx context.Context, arg InsertGDCErrorCountParams) error {
	_, err := q.db.ExecContext(ctx, insertGDCErrorCount, arg.Run, arg.GdcID, arg.Errors)
	return err
}

const insertGDCEvents = `-- name: InsertGDCEvents :exec
INSERT INTO events (run, gdc_id, ldc_id, events) VALUES (?, ?, NULL, ?)
`

type InsertGDCEventsParams struct {
	Run    int32         `db:"run" json:"run"`
	GdcID  sql.NullInt32 `db:"gdc_id" json:"gdc_id"`
	Events sql.NullInt64 `db:"events" json:"events"`
}

func (q *Queries) InsertGDCEvents(ctx context.Context, arg InsertGDCEventsParams) error {
	_, err := q.db.ExecContext(ctx, insertGDCEvents, arg.Run, arg.GdcID, arg.Events)
	return err
}

const insertLDCBytes = `-- name: InsertLDCBytes :exec
INSERT INTO data (run, gdc_id, ldc_id, bytes) VALUES (?, NULL, ?, ?)
`

type InsertLDCBytesParams struct {
	Run   int32         `db:"run" json:"run"`
	LdcID sql.NullInt32 `db:"ldc_id" json:"ldc_id"`
	Bytes sql.NullInt64 `db:"bytes" json:"bytes"`
}

func (q *Queries) InsertLDCBytes(ctx context.Context, arg InsertLDCBytesParams) error {
	_, err := q.db.ExecContext(ctx, insertLDCBytes, arg.Run, arg.LdcID, arg.Bytes)
	return err
}

const insertLDCErrorCount = `-- name: InsertLDCErrorCount :exec
INSERT INTO errors (run, gdc_id, ldc_id, errors) VALUES (?, NULL, ?, ?)
`

type InsertLDCErrorCountParams struct {
	Run    int32         `db:"run" json:"run"`
	LdcID  sql.NullInt32 `db:"ldc_id" json:"ldc_id"`
	Errors sql.NullInt64 `db:"errors" json:"errors"`
}

func (q *Queries) InsertLDCErrorCount(ctx context.Context, arg InsertLDCErrorCountParams) error {
	_, err := q.db.ExecContext(ctx, insertLDCErrorCount, arg.Run, arg.LdcID, arg.Errors)
	return err
}

const insertLDCEvents = `-- name: InsertLDCEvents :exec
INSERT INTO events (run, gdc_id, ldc_id, events) VALUES (?, NULL, ?, ?)
`

type InsertLDCEventsParams struct {
	Run    int32         `db:"run" json:"run"`
	LdcID  sql.NullInt32 `db:"ldc_id" json:"ldc_id"`
	Events sql.NullInt64 `db:"events" json:"events"`
}

func (q *Queries) InsertLDCEvents(ctx context.Context, arg InsertLDCEventsParams) error {
	_, err := q.db.ExecContext(ctx, insertLDCEvents, arg.Run, arg.LdcID, arg.Events)
	return err
}

const insertNewRun = `-- name: InsertNewRun :exec
INSERT INTO runs (start, stop) VALUES (NULL, NULL)
`

func (q *Queries) InsertNewRun(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, insertNewRun)
	return err
}

const insertRate = `-- name: InsertRate :exec
INSERT INTO rates (run, last_update, bytes, events, avgTriggerRate, avgByteRate) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertRateParams struct {
	Run            int32           `db:"run" json:"run"`
	LastUpdate     sql.NullTime    `db:"last_update" json:"last_update"`
	Bytes          sql.NullInt64   `db:"bytes" json:"bytes"`
	Events         sql.NullInt64   `db:"events" json:"events"`
	Avgtriggerrate sql.NullFloat64 `db:"avgtriggerrate" json:"avgtriggerrate"`
	Avgbyterate    sql.NullFloat64 `db:"avgbyterate" json:"avgbyterate"`
}

func (q *Queries) InsertRate(ctx context.Context, arg InsertRateParams) error {
	_, err := q.db.ExecContext(ctx, insertRate,
		arg.Run,
		arg.LastUpdate,
		arg.Bytes,
		arg.Events,
		arg.Avgtriggerrate,
		arg.Avgbyterate,
	)
	return err
}

const truncateDecoderParams = `-- name: TruncateDecoderParams :exec
TRUNCATE TABLE decoderParams
`

func (q *Queries) TruncateDecoderParams(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateDecoderParams)
	return err
}

const updateDecoderParams = `-- name: UpdateDecoderParams :exec
INSERT INTO decoderParams (
    ext_trigger, trg_code_1, trg_code_2, read_pmts, read_sipms,
    read_trigger, read_fibers, split_trigger, no_db, discard, host,
    user, passwd, db_name, write_data, use_blosc,
    blosc_algorithm, compression_level, bit_shuffle
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type UpdateDecoderParamsParams struct {
	ExtTrigger       int32        `db:"ext_trigger" json:"ext_trigger"`
	TrgCode1         int32        `db:"trg_code_1" json:"trg_code_1"`
	TrgCode2         int32        `db:"trg_code_2" json:"trg_code_2"`
	ReadPmts         sql.NullBool `db:"read_pmts" json:"read_pmts"`
	ReadSipms        sql.NullBool `db:"read_sipms" json:"read_sipms"`
	ReadTrigger      sql.NullBool `db:"read_trigger" json:"read_trigger"`
	ReadFibers       sql.NullBool `db:"read_fibers" json:"read_fibers"`
	SplitTrigger     sql.NullBool `db:"split_trigger" json:"split_trigger"`
	NoDb             sql.NullBool `db:"no_db" json:"no_db"`
	Discard          sql.NullBool `db:"discard" json:"discard"`
	Host             string       `db:"host" json:"host"`
	User             string       `db:"user" json:"user"`
	Passwd           string       `db:"passwd" json:"passwd"`
	DbName           string       `db:"db_name" json:"db_name"`
	WriteData        sql.NullBool `db:"write_data" json:"write_data"`
	UseBlosc         sql.NullBool `db:"use_blosc" json:"use_blosc"`
	BloscAlgorithm   string       `db:"blosc_algorithm" json:"blosc_algorithm"`
	CompressionLevel int32        `db:"compression_level" json:"compression_level"`
	BitShuffle       string       `db:"bit_shuffle" json:"bit_shuffle"`
}

func (q *Queries) UpdateDecoderParams(ctx context.Context, arg UpdateDecoderParamsParams) error {
	_, err := q.db.ExecContext(ctx, updateDecoderParams,
		arg.ExtTrigger,
		arg.TrgCode1,
		arg.TrgCode2,
		arg.ReadPmts,
		arg.ReadSipms,
		arg.ReadTrigger,
		arg.ReadFibers,
		arg.SplitTrigger,
		arg.NoDb,
		arg.Discard,
		arg.Host,
		arg.User,
		arg.Passwd,
		arg.DbName,
		arg.WriteData,
		arg.UseBlosc,
		arg.BloscAlgorithm,
		arg.CompressionLevel,
		arg.BitShuffle,
	)
	return err
}

const updateRate = `-- name: UpdateRate :exec
UPDATE rates SET last_update = ?, bytes = ?, events = ?, avgTriggerRate = ?, avgByteRate = ? WHERE run = ?
`

type UpdateRateParams struct {
	LastUpdate     sql.NullTime    `db:"last_update" json:"last_update"`
	Bytes          sql.NullInt64   `db:"bytes" json:"bytes"`
	Events         sql.NullInt64   `db:"events" json:"events"`
	Avgtriggerrate sql.NullFloat64 `db:"avgtriggerrate" json:"avgtriggerrate"`
	Avgbyterate    sql.NullFloat64 `db:"avgbyterate" json:"avgbyterate"`
	Run            int32           `db:"run" json:"run"`
}

func (q *Queries) UpdateRate(ctx context.Context, arg UpdateRateParams) error {
	_, err := q.db.ExecContext(ctx, updateRate,
		arg.LastUpdate,
		arg.Bytes,
		arg.Events,
		arg.Avgtriggerrate,
		arg.Avgbyterate,
		arg.Run,
	)
	return err
}

const updateRunStartTime = `-- name: UpdateRunStartTime :exec
UPDATE runs SET start = ?, stop = NULL WHERE id = ?
`

type UpdateRunStartTimeParams struct {
	Start sql.NullTime `db:"start" json:"start"`
	ID    int32        `db:"id" json:"id"`
}

func (q *Queries) UpdateRunStartTime(ctx context.Context, arg UpdateRunStartTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateRunStartTime, arg.Start, arg.ID)
	return err
}

const updateRunStopTime = `-- name: UpdateRunStopTime :exec
UPDATE runs SET stop = ? WHERE id = ?
`

type UpdateRunStopTimeParams struct {
	Stop sql.NullTime `db:"stop" json:"stop"`
	ID   int32        `db:"id" json:"id"`
}

func (q *Queries) UpdateRunStopTime(ctx context.Context, arg UpdateRunStopTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateRunStopTime, arg.Stop, arg.ID)
	return err
}

const upsertTopiParams = `-- name: UpsertTopiParams :exec
INSERT INTO topiParams (
  id, enabled, daemon_url, api_token, rabbitmq_address, rabbitmq_port,
  rabbitmq_user, rabbitmq_password, rabbitmq_vhost, exchange_name,
  control_queue, selected_configuration
) VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  enabled = VALUES(enabled), daemon_url = VALUES(daemon_url),
  api_token = VALUES(api_token), rabbitmq_address = VALUES(rabbitmq_address),
  rabbitmq_port = VALUES(rabbitmq_port), rabbitmq_user = VALUES(rabbitmq_user),
  rabbitmq_password = VALUES(rabbitmq_password), rabbitmq_vhost = VALUES(rabbitmq_vhost),
  exchange_name = VALUES(exchange_name), control_queue = VALUES(control_queue),
  selected_configuration = VALUES(selected_configuration)
`

type UpsertTopiParamsParams struct {
	Enabled               bool   `db:"enabled" json:"enabled"`
	DaemonUrl             string `db:"daemon_url" json:"daemon_url"`
	ApiToken              string `db:"api_token" json:"api_token"`
	RabbitmqAddress       string `db:"rabbitmq_address" json:"rabbitmq_address"`
	RabbitmqPort          int32  `db:"rabbitmq_port" json:"rabbitmq_port"`
	RabbitmqUser          string `db:"rabbitmq_user" json:"rabbitmq_user"`
	RabbitmqPassword      string `db:"rabbitmq_password" json:"rabbitmq_password"`
	RabbitmqVhost         string `db:"rabbitmq_vhost" json:"rabbitmq_vhost"`
	ExchangeName          string `db:"exchange_name" json:"exchange_name"`
	ControlQueue          string `db:"control_queue" json:"control_queue"`
	SelectedConfiguration string `db:"selected_configuration" json:"selected_configuration"`
}

func (q *Queries) UpsertTopiParams(ctx context.Context, arg UpsertTopiParamsParams) error {
	_, err := q.db.ExecContext(ctx, upsertTopiParams,
		arg.Enabled,
		arg.DaemonUrl,
		arg.ApiToken,
		arg.RabbitmqAddress,
		arg.RabbitmqPort,
		arg.RabbitmqUser,
		arg.RabbitmqPassword,
		arg.RabbitmqVhost,
		arg.ExchangeName,
		arg.ControlQueue,
		arg.SelectedConfiguration,
	)
	return err
}
