// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: equipments.sql

package database

import (
	"context"
	"database/sql"
)

const createEquipment = `-- name: CreateEquipment :execresult
INSERT INTO equipments (
    type, device_ip, host_ip, host_port, enabled, ldcID
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateEquipmentParams struct {
	Type     sql.NullInt32  `db:"type" json:"type"`
	DeviceIp sql.NullString `db:"device_ip" json:"device_ip"`
	HostIp   sql.NullString `db:"host_ip" json:"host_ip"`
	HostPort sql.NullInt32  `db:"host_port" json:"host_port"`
	Enabled  sql.NullBool   `db:"enabled" json:"enabled"`
	Ldcid    sql.NullInt32  `db:"ldcid" json:"ldcid"`
}

func (q *Queries) CreateEquipment(ctx context.Context, arg CreateEquipmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEquipment,
		arg.Type,
		arg.DeviceIp,
		arg.HostIp,
		arg.HostPort,
		arg.Enabled,
		arg.Ldcid,
	)
}

const deleteEquipment = `-- name: DeleteEquipment :exec
DELETE FROM equipments WHERE id = ?
`

func (q *Queries) DeleteEquipment(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteEquipment, id)
	return err
}

const getEquipment = `-- name: GetEquipment :one
SELECT id, type, device_ip, host_ip, host_port, enabled, ldcid FROM equipments WHERE id = ?
`

func (q *Queries) GetEquipment(ctx context.Context, id int32) (Equipment, error) {
	row := q.db.QueryRowContext(ctx, getEquipment, id)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.DeviceIp,
		&i.HostIp,
		&i.HostPort,
		&i.Enabled,
		&i.Ldcid,
	)
	return i, err
}

const listEquipments = `-- name: ListEquipments :many
SELECT id, type, device_ip, host_ip, host_port, enabled, ldcid FROM equipments ORDER BY id
`

func (q *Queries) ListEquipments(ctx context.Context) ([]Equipment, error) {
	rows, err := q.db.QueryContext(ctx, listEquipments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Equipment{}
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.DeviceIp,
			&i.HostIp,
			&i.HostPort,
			&i.Enabled,
			&i.Ldcid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEquipment = `-- name: UpdateEquipment :exec
UPDATE equipments 
SET type = ?, device_ip = ?, host_ip = ?, host_port = ?, 
    enabled = ?, ldcID = ?
WHERE id = ?
`

type UpdateEquipmentParams struct {
	Type     sql.NullInt32  `db:"type" json:"type"`
	DeviceIp sql.NullString `db:"device_ip" json:"device_ip"`
	HostIp   sql.NullString `db:"host_ip" json:"host_ip"`
	HostPort sql.NullInt32  `db:"host_port" json:"host_port"`
	Enabled  sql.NullBool   `db:"enabled" json:"enabled"`
	Ldcid    sql.NullInt32  `db:"ldcid" json:"ldcid"`
	ID       int32          `db:"id" json:"id"`
}

func (q *Queries) UpdateEquipment(ctx context.Context, arg UpdateEquipmentParams) error {
	_, err := q.db.ExecContext(ctx, updateEquipment,
		arg.Type,
		arg.DeviceIp,
		arg.HostIp,
		arg.HostPort,
		arg.Enabled,
		arg.Ldcid,
		arg.ID,
	)
	return err
}
