// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gdcs.sql

package database

import (
	"context"
	"database/sql"
)

const createGDC = `-- name: CreateGDC :execresult
INSERT INTO gdcs (
    name, hostname, ip, port, datapath, enabled, 
    writeOutput, decode, grpc_port, prometheus_port
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateGDCParams struct {
	Name           sql.NullString `db:"name" json:"name"`
	Hostname       sql.NullString `db:"hostname" json:"hostname"`
	Ip             sql.NullString `db:"ip" json:"ip"`
	Port           sql.NullInt32  `db:"port" json:"port"`
	Datapath       sql.NullString `db:"datapath" json:"datapath"`
	Enabled        sql.NullBool   `db:"enabled" json:"enabled"`
	Writeoutput    sql.NullBool   `db:"writeoutput" json:"writeoutput"`
	Decode         sql.NullBool   `db:"decode" json:"decode"`
	GrpcPort       sql.NullInt32  `db:"grpc_port" json:"grpc_port"`
	PrometheusPort sql.NullInt32  `db:"prometheus_port" json:"prometheus_port"`
}

func (q *Queries) CreateGDC(ctx context.Context, arg CreateGDCParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGDC,
		arg.Name,
		arg.Hostname,
		arg.Ip,
		arg.Port,
		arg.Datapath,
		arg.Enabled,
		arg.Writeoutput,
		arg.Decode,
		arg.GrpcPort,
		arg.PrometheusPort,
	)
}

const deleteGDC = `-- name: DeleteGDC :exec
DELETE FROM gdcs WHERE id = ?
`

func (q *Queries) DeleteGDC(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteGDC, id)
	return err
}

const getGDC = `-- name: GetGDC :one
SELECT id, name, hostname, ip, port, grpc_port, prometheus_port, datapath, enabled, writeoutput, decode FROM gdcs WHERE id = ?
`

func (q *Queries) GetGDC(ctx context.Context, id int32) (Gdc, error) {
	row := q.db.QueryRowContext(ctx, getGDC, id)
	var i Gdc
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.Ip,
		&i.Port,
		&i.GrpcPort,
		&i.PrometheusPort,
		&i.Datapath,
		&i.Enabled,
		&i.Writeoutput,
		&i.Decode,
	)
	return i, err
}

const listGDCs = `-- name: ListGDCs :many
SELECT id, name, hostname, ip, port, grpc_port, prometheus_port, datapath, enabled, writeoutput, decode FROM gdcs ORDER BY name
`

func (q *Queries) ListGDCs(ctx context.Context) ([]Gdc, error) {
	rows, err := q.db.QueryContext(ctx, listGDCs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gdc{}
	for rows.Next() {
		var i Gdc
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.Ip,
			&i.Port,
			&i.GrpcPort,
			&i.PrometheusPort,
			&i.Datapath,
			&i.Enabled,
			&i.Writeoutput,
			&i.Decode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGDC = `-- name: UpdateGDC :exec
UPDATE gdcs 
SET name = ?, hostname = ?, ip = ?, port = ?, 
    datapath = ?, enabled = ?, writeOutput = ?, 
    decode = ?, grpc_port = ?, prometheus_port = ?
WHERE id = ?
`

type UpdateGDCParams struct {
	Name           sql.NullString `db:"name" json:"name"`
	Hostname       sql.NullString `db:"hostname" json:"hostname"`
	Ip             sql.NullString `db:"ip" json:"ip"`
	Port           sql.NullInt32  `db:"port" json:"port"`
	Datapath       sql.NullString `db:"datapath" json:"datapath"`
	Enabled        sql.NullBool   `db:"enabled" json:"enabled"`
	Writeoutput    sql.NullBool   `db:"writeoutput" json:"writeoutput"`
	Decode         sql.NullBool   `db:"decode" json:"decode"`
	GrpcPort       sql.NullInt32  `db:"grpc_port" json:"grpc_port"`
	PrometheusPort sql.NullInt32  `db:"prometheus_port" json:"prometheus_port"`
	ID             int32          `db:"id" json:"id"`
}

func (q *Queries) UpdateGDC(ctx context.Context, arg UpdateGDCParams) error {
	_, err := q.db.ExecContext(ctx, updateGDC,
		arg.Name,
		arg.Hostname,
		arg.Ip,
		arg.Port,
		arg.Datapath,
		arg.Enabled,
		arg.Writeoutput,
		arg.Decode,
		arg.GrpcPort,
		arg.PrometheusPort,
		arg.ID,
	)
	return err
}
