// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ldcs.sql

package database

import (
	"context"
	"database/sql"
)

const createLDC = `-- name: CreateLDC :execresult
INSERT INTO ldcs (
    name, hostname, ip, enabled, grpc_port, prometheus_port
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateLDCParams struct {
	Name           sql.NullString `db:"name" json:"name"`
	Hostname       sql.NullString `db:"hostname" json:"hostname"`
	Ip             sql.NullString `db:"ip" json:"ip"`
	Enabled        sql.NullBool   `db:"enabled" json:"enabled"`
	GrpcPort       sql.NullInt32  `db:"grpc_port" json:"grpc_port"`
	PrometheusPort sql.NullInt32  `db:"prometheus_port" json:"prometheus_port"`
}

func (q *Queries) CreateLDC(ctx context.Context, arg CreateLDCParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLDC,
		arg.Name,
		arg.Hostname,
		arg.Ip,
		arg.Enabled,
		arg.GrpcPort,
		arg.PrometheusPort,
	)
}

const deleteLDC = `-- name: DeleteLDC :exec
DELETE FROM ldcs WHERE id = ?
`

func (q *Queries) DeleteLDC(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteLDC, id)
	return err
}

const getLDC = `-- name: GetLDC :one
SELECT id, name, hostname, ip, grpc_port, prometheus_port, enabled FROM ldcs WHERE id = ?
`

func (q *Queries) GetLDC(ctx context.Context, id int32) (Ldc, error) {
	row := q.db.QueryRowContext(ctx, getLDC, id)
	var i Ldc
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.Ip,
		&i.GrpcPort,
		&i.PrometheusPort,
		&i.Enabled,
	)
	return i, err
}

const listLDCs = `-- name: ListLDCs :many
SELECT id, name, hostname, ip, grpc_port, prometheus_port, enabled FROM ldcs ORDER BY name
`

func (q *Queries) ListLDCs(ctx context.Context) ([]Ldc, error) {
	rows, err := q.db.QueryContext(ctx, listLDCs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ldc{}
	for rows.Next() {
		var i Ldc
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.Ip,
			&i.GrpcPort,
			&i.PrometheusPort,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLDC = `-- name: UpdateLDC :exec
UPDATE ldcs 
SET name = ?, hostname = ?, ip = ?, enabled = ?, 
    grpc_port = ?, prometheus_port = ?
WHERE id = ?
`

type UpdateLDCParams struct {
	Name           sql.NullString `db:"name" json:"name"`
	Hostname       sql.NullString `db:"hostname" json:"hostname"`
	Ip             sql.NullString `db:"ip" json:"ip"`
	Enabled        sql.NullBool   `db:"enabled" json:"enabled"`
	GrpcPort       sql.NullInt32  `db:"grpc_port" json:"grpc_port"`
	PrometheusPort sql.NullInt32  `db:"prometheus_port" json:"prometheus_port"`
	ID             int32          `db:"id" json:"id"`
}

func (q *Queries) UpdateLDC(ctx context.Context, arg UpdateLDCParams) error {
	_, err := q.db.ExecContext(ctx, updateLDC,
		arg.Name,
		arg.Hostname,
		arg.Ip,
		arg.Enabled,
		arg.GrpcPort,
		arg.PrometheusPort,
		arg.ID,
	)
	return err
}
