// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Datum struct {
	Run   int32         `db:"run" json:"run"`
	GdcID sql.NullInt32 `db:"gdc_id" json:"gdc_id"`
	LdcID sql.NullInt32 `db:"ldc_id" json:"ldc_id"`
	Bytes sql.NullInt64 `db:"bytes" json:"bytes"`
}

type Decoderparam struct {
	ExtTrigger       int32        `db:"ext_trigger" json:"ext_trigger"`
	TrgCode1         int32        `db:"trg_code_1" json:"trg_code_1"`
	TrgCode2         int32        `db:"trg_code_2" json:"trg_code_2"`
	ReadPmts         sql.NullBool `db:"read_pmts" json:"read_pmts"`
	ReadSipms        sql.NullBool `db:"read_sipms" json:"read_sipms"`
	ReadTrigger      sql.NullBool `db:"read_trigger" json:"read_trigger"`
	SplitTrigger     sql.NullBool `db:"split_trigger" json:"split_trigger"`
	NoDb             sql.NullBool `db:"no_db" json:"no_db"`
	Discard          sql.NullBool `db:"discard" json:"discard"`
	Host             string       `db:"host" json:"host"`
	User             string       `db:"user" json:"user"`
	Passwd           string       `db:"passwd" json:"passwd"`
	DbName           string       `db:"db_name" json:"db_name"`
	WriteData        sql.NullBool `db:"write_data" json:"write_data"`
	UseBlosc         sql.NullBool `db:"use_blosc" json:"use_blosc"`
	BloscAlgorithm   string       `db:"blosc_algorithm" json:"blosc_algorithm"`
	CompressionLevel int32        `db:"compression_level" json:"compression_level"`
	BitShuffle       string       `db:"bit_shuffle" json:"bit_shuffle"`
}

type Duckparam struct {
	Filesize         int32  `db:"filesize" json:"filesize"`
	Experiment       string `db:"experiment" json:"experiment"`
	Packetsize       int32  `db:"packetsize" json:"packetsize"`
	Npacketsinbuffer int32  `db:"npacketsinbuffer" json:"npacketsinbuffer"`
	Buffertimeout    int32  `db:"buffertimeout" json:"buffertimeout"`
	Equipmentdatach  int32  `db:"equipmentdatach" json:"equipmentdatach"`
	Receivech        int32  `db:"receivech" json:"receivech"`
	Datach           int32  `db:"datach" json:"datach"`
	Metricsch        int32  `db:"metricsch" json:"metricsch"`
	Tcpconnectionsch int32  `db:"tcpconnectionsch" json:"tcpconnectionsch"`
	Decoderch        int32  `db:"decoderch" json:"decoderch"`
	Decoderworkers   int32  `db:"decoderworkers" json:"decoderworkers"`
	Writerch         int32  `db:"writerch" json:"writerch"`
}

type Equipment struct {
	ID       int32          `db:"id" json:"id"`
	Type     sql.NullInt32  `db:"type" json:"type"`
	DeviceIp sql.NullString `db:"device_ip" json:"device_ip"`
	HostIp   sql.NullString `db:"host_ip" json:"host_ip"`
	HostPort sql.NullInt32  `db:"host_port" json:"host_port"`
	Enabled  sql.NullBool   `db:"enabled" json:"enabled"`
	Ldcid    sql.NullInt32  `db:"ldcid" json:"ldcid"`
}

type Error struct {
	Run    int32         `db:"run" json:"run"`
	GdcID  sql.NullInt32 `db:"gdc_id" json:"gdc_id"`
	LdcID  sql.NullInt32 `db:"ldc_id" json:"ldc_id"`
	Errors sql.NullInt64 `db:"errors" json:"errors"`
}

type Event struct {
	Run    int32         `db:"run" json:"run"`
	GdcID  sql.NullInt32 `db:"gdc_id" json:"gdc_id"`
	LdcID  sql.NullInt32 `db:"ldc_id" json:"ldc_id"`
	Events sql.NullInt64 `db:"events" json:"events"`
}

type Gdc struct {
	ID             int32          `db:"id" json:"id"`
	Name           sql.NullString `db:"name" json:"name"`
	Hostname       sql.NullString `db:"hostname" json:"hostname"`
	Ip             sql.NullString `db:"ip" json:"ip"`
	Port           sql.NullInt32  `db:"port" json:"port"`
	GrpcPort       sql.NullInt32  `db:"grpc_port" json:"grpc_port"`
	PrometheusPort sql.NullInt32  `db:"prometheus_port" json:"prometheus_port"`
	Datapath       sql.NullString `db:"datapath" json:"datapath"`
	Enabled        sql.NullBool   `db:"enabled" json:"enabled"`
	Writeoutput    sql.NullBool   `db:"writeoutput" json:"writeoutput"`
	Decode         sql.NullBool   `db:"decode" json:"decode"`
}

type Ldc struct {
	ID             int32          `db:"id" json:"id"`
	Name           sql.NullString `db:"name" json:"name"`
	Hostname       sql.NullString `db:"hostname" json:"hostname"`
	Ip             sql.NullString `db:"ip" json:"ip"`
	GrpcPort       sql.NullInt32  `db:"grpc_port" json:"grpc_port"`
	PrometheusPort sql.NullInt32  `db:"prometheus_port" json:"prometheus_port"`
	Enabled        sql.NullBool   `db:"enabled" json:"enabled"`
}

type Rate struct {
	Run            int32           `db:"run" json:"run"`
	LastUpdate     sql.NullTime    `db:"last_update" json:"last_update"`
	Avgbyterate    sql.NullFloat64 `db:"avgbyterate" json:"avgbyterate"`
	Avgtriggerrate sql.NullFloat64 `db:"avgtriggerrate" json:"avgtriggerrate"`
	Bytes          sql.NullInt64   `db:"bytes" json:"bytes"`
	Events         sql.NullInt64   `db:"events" json:"events"`
}

type Run struct {
	ID    int32        `db:"id" json:"id"`
	Start sql.NullTime `db:"start" json:"start"`
	Stop  sql.NullTime `db:"stop" json:"stop"`
}

type Simulatorparam struct {
	Equipmentid int32   `db:"equipmentid" json:"equipmentid"`
	Filepath    string  `db:"filepath" json:"filepath"`
	Replayrate  float64 `db:"replayrate" json:"replayrate"`
	Loopmode    bool    `db:"loopmode" json:"loopmode"`
	Maxevents   int32   `db:"maxevents" json:"maxevents"`
	Packetsize  int32   `db:"packetsize" json:"packetsize"`
}

type Testdeviceparam struct {
	EquipmentID        int32   `db:"equipment_id" json:"equipment_id"`
	EventRateMs        int32   `db:"event_rate_ms" json:"event_rate_ms"`
	PacketsPerEvent    int32   `db:"packets_per_event" json:"packets_per_event"`
	PacketSize         int32   `db:"packet_size" json:"packet_size"`
	ErrorInjectionRate float64 `db:"error_injection_rate" json:"error_injection_rate"`
	MaxEvents          int32   `db:"max_events" json:"max_events"`
}
