// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateEquipment(ctx context.Context, arg CreateEquipmentParams) (sql.Result, error)
	CreateGDC(ctx context.Context, arg CreateGDCParams) (sql.Result, error)
	CreateLDC(ctx context.Context, arg CreateLDCParams) (sql.Result, error)
	CreateSimulatorParams(ctx context.Context, arg CreateSimulatorParamsParams) (sql.Result, error)
	DeleteEquipment(ctx context.Context, id int32) error
	DeleteGDC(ctx context.Context, id int32) error
	DeleteLDC(ctx context.Context, id int32) error
	DeleteSimulatorParams(ctx context.Context, equipmentid int32) error
	GetDecoderParams(ctx context.Context) (Decoderparam, error)
	GetDisabledEquipments(ctx context.Context) ([]Equipment, error)
	GetDisabledGDCs(ctx context.Context) ([]Gdc, error)
	GetDisabledLDCs(ctx context.Context) ([]Ldc, error)
	GetDuckParams(ctx context.Context) (Duckparam, error)
	GetEquipment(ctx context.Context, id int32) (Equipment, error)
	GetGDC(ctx context.Context, id int32) (Gdc, error)
	GetGDCsWithoutWrite(ctx context.Context) ([]Gdc, error)
	GetLDC(ctx context.Context, id int32) (Ldc, error)
	GetLatestRun(ctx context.Context) (int32, error)
	// Run management queries
	GetLatestRunWithTimestamp(ctx context.Context) (Run, error)
	// Rate management queries
	GetRateByRun(ctx context.Context, run int32) (int32, error)
	GetSimulatorParams(ctx context.Context, equipmentid int32) (Simulatorparam, error)
	GetTestDeviceParams(ctx context.Context) ([]Testdeviceparam, error)
	InsertGDCBytes(ctx context.Context, arg InsertGDCBytesParams) error
	InsertGDCErrorCount(ctx context.Context, arg InsertGDCErrorCountParams) error
	InsertGDCEvents(ctx context.Context, arg InsertGDCEventsParams) error
	InsertLDCBytes(ctx context.Context, arg InsertLDCBytesParams) error
	InsertLDCErrorCount(ctx context.Context, arg InsertLDCErrorCountParams) error
	InsertLDCEvents(ctx context.Context, arg InsertLDCEventsParams) error
	InsertNewRun(ctx context.Context) error
	InsertRate(ctx context.Context, arg InsertRateParams) error
	ListEquipments(ctx context.Context) ([]Equipment, error)
	ListGDCs(ctx context.Context) ([]Gdc, error)
	ListLDCs(ctx context.Context) ([]Ldc, error)
	ListSimulatorParams(ctx context.Context) ([]Simulatorparam, error)
	TruncateDecoderParams(ctx context.Context) error
	UpdateDecoderParams(ctx context.Context, arg UpdateDecoderParamsParams) error
	UpdateEquipment(ctx context.Context, arg UpdateEquipmentParams) error
	UpdateGDC(ctx context.Context, arg UpdateGDCParams) error
	UpdateLDC(ctx context.Context, arg UpdateLDCParams) error
	UpdateRate(ctx context.Context, arg UpdateRateParams) error
	UpdateRunStartTime(ctx context.Context, arg UpdateRunStartTimeParams) error
	UpdateRunStopTime(ctx context.Context, arg UpdateRunStopTimeParams) error
	UpdateSimulatorParams(ctx context.Context, arg UpdateSimulatorParamsParams) error
}

var _ Querier = (*Queries)(nil)
