// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: simulators.sql

package database

import (
	"context"
	"database/sql"
)

const createSimulatorParams = `-- name: CreateSimulatorParams :execresult
INSERT INTO simulatorParams (
    equipmentID, filePath, replayrate, loopmode, maxevents, packetsize
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSimulatorParamsParams struct {
	Equipmentid int32   `db:"equipmentid" json:"equipmentid"`
	Filepath    string  `db:"filepath" json:"filepath"`
	Replayrate  float64 `db:"replayrate" json:"replayrate"`
	Loopmode    bool    `db:"loopmode" json:"loopmode"`
	Maxevents   int32   `db:"maxevents" json:"maxevents"`
	Packetsize  int32   `db:"packetsize" json:"packetsize"`
}

func (q *Queries) CreateSimulatorParams(ctx context.Context, arg CreateSimulatorParamsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSimulatorParams,
		arg.Equipmentid,
		arg.Filepath,
		arg.Replayrate,
		arg.Loopmode,
		arg.Maxevents,
		arg.Packetsize,
	)
}

const deleteSimulatorParams = `-- name: DeleteSimulatorParams :exec
DELETE FROM simulatorParams WHERE equipmentID = ?
`

func (q *Queries) DeleteSimulatorParams(ctx context.Context, equipmentid int32) error {
	_, err := q.db.ExecContext(ctx, deleteSimulatorParams, equipmentid)
	return err
}

const getSimulatorParams = `-- name: GetSimulatorParams :one
SELECT equipmentid, filepath, replayrate, loopmode, maxevents, packetsize FROM simulatorParams WHERE equipmentID = ?
`

func (q *Queries) GetSimulatorParams(ctx context.Context, equipmentid int32) (Simulatorparam, error) {
	row := q.db.QueryRowContext(ctx, getSimulatorParams, equipmentid)
	var i Simulatorparam
	err := row.Scan(
		&i.Equipmentid,
		&i.Filepath,
		&i.Replayrate,
		&i.Loopmode,
		&i.Maxevents,
		&i.Packetsize,
	)
	return i, err
}

const listSimulatorParams = `-- name: ListSimulatorParams :many
SELECT equipmentid, filepath, replayrate, loopmode, maxevents, packetsize FROM simulatorParams ORDER BY equipmentID
`

func (q *Queries) ListSimulatorParams(ctx context.Context) ([]Simulatorparam, error) {
	rows, err := q.db.QueryContext(ctx, listSimulatorParams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Simulatorparam{}
	for rows.Next() {
		var i Simulatorparam
		if err := rows.Scan(
			&i.Equipmentid,
			&i.Filepath,
			&i.Replayrate,
			&i.Loopmode,
			&i.Maxevents,
			&i.Packetsize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSimulatorParams = `-- name: UpdateSimulatorParams :exec
UPDATE simulatorParams
SET filePath = ?, replayrate = ?, loopmode = ?, maxevents = ?, packetsize = ?
WHERE equipmentID = ?
`

type UpdateSimulatorParamsParams struct {
	Filepath    string  `db:"filepath" json:"filepath"`
	Replayrate  float64 `db:"replayrate" json:"replayrate"`
	Loopmode    bool    `db:"loopmode" json:"loopmode"`
	Maxevents   int32   `db:"maxevents" json:"maxevents"`
	Packetsize  int32   `db:"packetsize" json:"packetsize"`
	Equipmentid int32   `db:"equipmentid" json:"equipmentid"`
}

func (q *Queries) UpdateSimulatorParams(ctx context.Context, arg UpdateSimulatorParamsParams) error {
	_, err := q.db.ExecContext(ctx, updateSimulatorParams,
		arg.Filepath,
		arg.Replayrate,
		arg.Loopmode,
		arg.Maxevents,
		arg.Packetsize,
		arg.Equipmentid,
	)
	return err
}
