// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DuckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DuckRequest) Reset() {
	*x = DuckRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuckRequest) ProtoMessage() {}

func (x *DuckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DuckRequest.ProtoReflect.Descriptor instead.
func (*DuckRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

type DuckReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DuckReply) Reset() {
	*x = DuckReply{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuckReply) ProtoMessage() {}

func (x *DuckReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DuckReply.ProtoReflect.Descriptor instead.
func (*DuckReply) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *DuckReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *PingReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RunStatisticsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        int64                  `protobuf:"varint,1,opt,name=events,proto3" json:"events,omitempty"`
	Bytes         int64                  `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Errors        int64                  `protobuf:"varint,3,opt,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStatisticsReply) Reset() {
	*x = RunStatisticsReply{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStatisticsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStatisticsReply) ProtoMessage() {}

func (x *RunStatisticsReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStatisticsReply.ProtoReflect.Descriptor instead.
func (*RunStatisticsReply) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *RunStatisticsReply) GetEvents() int64 {
	if x != nil {
		return x.Events
	}
	return 0
}

func (x *RunStatisticsReply) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *RunStatisticsReply) GetErrors() int64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\n" +
	"rpcControl\"\r\n" +
	"\vDuckRequest\"%\n" +
	"\tDuckReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\tPingReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Z\n" +
	"\x12RunStatisticsReply\x12\x16\n" +
	"\x06events\x18\x01 \x01(\x03R\x06events\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x03R\x05bytes\x12\x16\n" +
	"\x06errors\x18\x03 \x01(\x03R\x06errors2\xd5\x02\n" +
	"\n" +
	"RunControl\x12<\n" +
	"\bStartRun\x12\x17.rpcControl.DuckRequest\x1a\x15.rpcControl.DuckReply\"\x00\x12;\n" +
	"\aStopRun\x12\x17.rpcControl.DuckRequest\x1a\x15.rpcControl.DuckReply\"\x00\x12<\n" +
	"\bGetState\x12\x17.rpcControl.DuckRequest\x1a\x15.rpcControl.DuckReply\"\x00\x12?\n" +
	"\vPingDevices\x12\x17.rpcControl.DuckRequest\x1a\x15.rpcControl.PingReply\"\x00\x12M\n" +
	"\x10GetRunStatistics\x12\x17.rpcControl.DuckRequest\x1a\x1e.rpcControl.RunStatisticsReply\"\x00B-Z+github.com/jmbenlloch/next_duck/rpc/controlb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_control_proto_goTypes = []any{
	(*DuckRequest)(nil),        // 0: rpcControl.DuckRequest
	(*DuckReply)(nil),          // 1: rpcControl.DuckReply
	(*PingReply)(nil),          // 2: rpcControl.PingReply
	(*RunStatisticsReply)(nil), // 3: rpcControl.RunStatisticsReply
}
var file_control_proto_depIdxs = []int32{
	0, // 0: rpcControl.RunControl.StartRun:input_type -> rpcControl.DuckRequest
	0, // 1: rpcControl.RunControl.StopRun:input_type -> rpcControl.DuckRequest
	0, // 2: rpcControl.RunControl.GetState:input_type -> rpcControl.DuckRequest
	0, // 3: rpcControl.RunControl.PingDevices:input_type -> rpcControl.DuckRequest
	0, // 4: rpcControl.RunControl.GetRunStatistics:input_type -> rpcControl.DuckRequest
	1, // 5: rpcControl.RunControl.StartRun:output_type -> rpcControl.DuckReply
	1, // 6: rpcControl.RunControl.StopRun:output_type -> rpcControl.DuckReply
	1, // 7: rpcControl.RunControl.GetState:output_type -> rpcControl.DuckReply
	2, // 8: rpcControl.RunControl.PingDevices:output_type -> rpcControl.PingReply
	3, // 9: rpcControl.RunControl.GetRunStatistics:output_type -> rpcControl.RunStatisticsReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
