// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api.proto

package apiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/jmbenlloch/next_duck/rpc/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DuckAPIName is the fully-qualified name of the DuckAPI service.
	DuckAPIName = "apiService.DuckAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DuckAPIStartRunProcedure is the fully-qualified name of the DuckAPI's StartRun RPC.
	DuckAPIStartRunProcedure = "/apiService.DuckAPI/StartRun"
	// DuckAPIStopRunProcedure is the fully-qualified name of the DuckAPI's StopRun RPC.
	DuckAPIStopRunProcedure = "/apiService.DuckAPI/StopRun"
	// DuckAPIForceStopRunProcedure is the fully-qualified name of the DuckAPI's ForceStopRun RPC.
	DuckAPIForceStopRunProcedure = "/apiService.DuckAPI/ForceStopRun"
	// DuckAPIGetProcessStatesProcedure is the fully-qualified name of the DuckAPI's GetProcessStates
	// RPC.
	DuckAPIGetProcessStatesProcedure = "/apiService.DuckAPI/GetProcessStates"
	// DuckAPIRestartServicesProcedure is the fully-qualified name of the DuckAPI's RestartServices RPC.
	DuckAPIRestartServicesProcedure = "/apiService.DuckAPI/RestartServices"
	// DuckAPICreateGDCProcedure is the fully-qualified name of the DuckAPI's CreateGDC RPC.
	DuckAPICreateGDCProcedure = "/apiService.DuckAPI/CreateGDC"
	// DuckAPIGetGDCsProcedure is the fully-qualified name of the DuckAPI's GetGDCs RPC.
	DuckAPIGetGDCsProcedure = "/apiService.DuckAPI/GetGDCs"
	// DuckAPIGetGDCProcedure is the fully-qualified name of the DuckAPI's GetGDC RPC.
	DuckAPIGetGDCProcedure = "/apiService.DuckAPI/GetGDC"
	// DuckAPIUpdateGDCProcedure is the fully-qualified name of the DuckAPI's UpdateGDC RPC.
	DuckAPIUpdateGDCProcedure = "/apiService.DuckAPI/UpdateGDC"
	// DuckAPIDeleteGDCProcedure is the fully-qualified name of the DuckAPI's DeleteGDC RPC.
	DuckAPIDeleteGDCProcedure = "/apiService.DuckAPI/DeleteGDC"
	// DuckAPICreateLDCProcedure is the fully-qualified name of the DuckAPI's CreateLDC RPC.
	DuckAPICreateLDCProcedure = "/apiService.DuckAPI/CreateLDC"
	// DuckAPIGetLDCsProcedure is the fully-qualified name of the DuckAPI's GetLDCs RPC.
	DuckAPIGetLDCsProcedure = "/apiService.DuckAPI/GetLDCs"
	// DuckAPIGetLDCProcedure is the fully-qualified name of the DuckAPI's GetLDC RPC.
	DuckAPIGetLDCProcedure = "/apiService.DuckAPI/GetLDC"
	// DuckAPIUpdateLDCProcedure is the fully-qualified name of the DuckAPI's UpdateLDC RPC.
	DuckAPIUpdateLDCProcedure = "/apiService.DuckAPI/UpdateLDC"
	// DuckAPIDeleteLDCProcedure is the fully-qualified name of the DuckAPI's DeleteLDC RPC.
	DuckAPIDeleteLDCProcedure = "/apiService.DuckAPI/DeleteLDC"
	// DuckAPICreateEquipmentProcedure is the fully-qualified name of the DuckAPI's CreateEquipment RPC.
	DuckAPICreateEquipmentProcedure = "/apiService.DuckAPI/CreateEquipment"
	// DuckAPIGetEquipmentsProcedure is the fully-qualified name of the DuckAPI's GetEquipments RPC.
	DuckAPIGetEquipmentsProcedure = "/apiService.DuckAPI/GetEquipments"
	// DuckAPIGetEquipmentProcedure is the fully-qualified name of the DuckAPI's GetEquipment RPC.
	DuckAPIGetEquipmentProcedure = "/apiService.DuckAPI/GetEquipment"
	// DuckAPIUpdateEquipmentProcedure is the fully-qualified name of the DuckAPI's UpdateEquipment RPC.
	DuckAPIUpdateEquipmentProcedure = "/apiService.DuckAPI/UpdateEquipment"
	// DuckAPIDeleteEquipmentProcedure is the fully-qualified name of the DuckAPI's DeleteEquipment RPC.
	DuckAPIDeleteEquipmentProcedure = "/apiService.DuckAPI/DeleteEquipment"
	// DuckAPIGetDecoderConfigurationProcedure is the fully-qualified name of the DuckAPI's
	// GetDecoderConfiguration RPC.
	DuckAPIGetDecoderConfigurationProcedure = "/apiService.DuckAPI/GetDecoderConfiguration"
	// DuckAPIUpdateDecoderConfigurationProcedure is the fully-qualified name of the DuckAPI's
	// UpdateDecoderConfiguration RPC.
	DuckAPIUpdateDecoderConfigurationProcedure = "/apiService.DuckAPI/UpdateDecoderConfiguration"
	// DuckAPIGetRunNumberProcedure is the fully-qualified name of the DuckAPI's GetRunNumber RPC.
	DuckAPIGetRunNumberProcedure = "/apiService.DuckAPI/GetRunNumber"
	// DuckAPICheckDisabledProcedure is the fully-qualified name of the DuckAPI's CheckDisabled RPC.
	DuckAPICheckDisabledProcedure = "/apiService.DuckAPI/CheckDisabled"
	// DuckAPIGetTokenProcedure is the fully-qualified name of the DuckAPI's GetToken RPC.
	DuckAPIGetTokenProcedure = "/apiService.DuckAPI/GetToken"
	// DuckAPIStartTestDevicesProcedure is the fully-qualified name of the DuckAPI's StartTestDevices
	// RPC.
	DuckAPIStartTestDevicesProcedure = "/apiService.DuckAPI/StartTestDevices"
	// DuckAPIStopTestDevicesProcedure is the fully-qualified name of the DuckAPI's StopTestDevices RPC.
	DuckAPIStopTestDevicesProcedure = "/apiService.DuckAPI/StopTestDevices"
	// DuckAPIGetTestDevicesStatesProcedure is the fully-qualified name of the DuckAPI's
	// GetTestDevicesStates RPC.
	DuckAPIGetTestDevicesStatesProcedure = "/apiService.DuckAPI/GetTestDevicesStates"
	// DuckAPIListTestDevicesProcedure is the fully-qualified name of the DuckAPI's ListTestDevices RPC.
	DuckAPIListTestDevicesProcedure = "/apiService.DuckAPI/ListTestDevices"
	// DuckAPIGetTestDeviceStatisticsProcedure is the fully-qualified name of the DuckAPI's
	// GetTestDeviceStatistics RPC.
	DuckAPIGetTestDeviceStatisticsProcedure = "/apiService.DuckAPI/GetTestDeviceStatistics"
)

// DuckAPIClient is a client for the apiService.DuckAPI service.
type DuckAPIClient interface {
	// Run Control Operations
	StartRun(context.Context, *connect.Request[api.StartRunRequest]) (*connect.Response[api.StartRunResponse], error)
	StopRun(context.Context, *connect.Request[api.StopRunRequest]) (*connect.Response[api.StopRunResponse], error)
	ForceStopRun(context.Context, *connect.Request[api.ForceStopRunRequest]) (*connect.Response[api.ForceStopRunResponse], error)
	GetProcessStates(context.Context, *connect.Request[api.GetProcessStatesRequest]) (*connect.Response[api.GetProcessStatesResponse], error)
	RestartServices(context.Context, *connect.Request[api.RestartServicesRequest]) (*connect.Response[api.RestartServicesResponse], error)
	// GDC Management
	CreateGDC(context.Context, *connect.Request[api.CreateGDCRequest]) (*connect.Response[api.CreateGDCResponse], error)
	GetGDCs(context.Context, *connect.Request[api.GetGDCsRequest]) (*connect.Response[api.GetGDCsResponse], error)
	GetGDC(context.Context, *connect.Request[api.GetGDCRequest]) (*connect.Response[api.GetGDCResponse], error)
	UpdateGDC(context.Context, *connect.Request[api.UpdateGDCRequest]) (*connect.Response[api.UpdateGDCResponse], error)
	DeleteGDC(context.Context, *connect.Request[api.DeleteGDCRequest]) (*connect.Response[api.DeleteGDCResponse], error)
	// LDC Management
	CreateLDC(context.Context, *connect.Request[api.CreateLDCRequest]) (*connect.Response[api.CreateLDCResponse], error)
	GetLDCs(context.Context, *connect.Request[api.GetLDCsRequest]) (*connect.Response[api.GetLDCsResponse], error)
	GetLDC(context.Context, *connect.Request[api.GetLDCRequest]) (*connect.Response[api.GetLDCResponse], error)
	UpdateLDC(context.Context, *connect.Request[api.UpdateLDCRequest]) (*connect.Response[api.UpdateLDCResponse], error)
	DeleteLDC(context.Context, *connect.Request[api.DeleteLDCRequest]) (*connect.Response[api.DeleteLDCResponse], error)
	// Equipment Management
	CreateEquipment(context.Context, *connect.Request[api.CreateEquipmentRequest]) (*connect.Response[api.CreateEquipmentResponse], error)
	GetEquipments(context.Context, *connect.Request[api.GetEquipmentsRequest]) (*connect.Response[api.GetEquipmentsResponse], error)
	GetEquipment(context.Context, *connect.Request[api.GetEquipmentRequest]) (*connect.Response[api.GetEquipmentResponse], error)
	UpdateEquipment(context.Context, *connect.Request[api.UpdateEquipmentRequest]) (*connect.Response[api.UpdateEquipmentResponse], error)
	DeleteEquipment(context.Context, *connect.Request[api.DeleteEquipmentRequest]) (*connect.Response[api.DeleteEquipmentResponse], error)
	// Decoder Configuration
	GetDecoderConfiguration(context.Context, *connect.Request[api.GetDecoderConfigurationRequest]) (*connect.Response[api.GetDecoderConfigurationResponse], error)
	UpdateDecoderConfiguration(context.Context, *connect.Request[api.UpdateDecoderConfigurationRequest]) (*connect.Response[api.UpdateDecoderConfigurationResponse], error)
	// Run Information
	GetRunNumber(context.Context, *connect.Request[api.GetRunNumberRequest]) (*connect.Response[api.GetRunNumberResponse], error)
	CheckDisabled(context.Context, *connect.Request[api.CheckDisabledRequest]) (*connect.Response[api.CheckDisabledResponse], error)
	// Authentication
	GetToken(context.Context, *connect.Request[api.GetTokenRequest]) (*connect.Response[api.GetTokenResponse], error)
	// Test Device Management
	StartTestDevices(context.Context, *connect.Request[api.StartTestDevicesRequest]) (*connect.Response[api.StartTestDevicesResponse], error)
	StopTestDevices(context.Context, *connect.Request[api.StopTestDevicesRequest]) (*connect.Response[api.StopTestDevicesResponse], error)
	GetTestDevicesStates(context.Context, *connect.Request[api.GetTestDevicesStatesRequest]) (*connect.Response[api.GetTestDevicesStatesResponse], error)
	ListTestDevices(context.Context, *connect.Request[api.ListTestDevicesRequest]) (*connect.Response[api.ListTestDevicesResponse], error)
	GetTestDeviceStatistics(context.Context, *connect.Request[api.GetTestDeviceStatisticsRequest]) (*connect.Response[api.GetTestDeviceStatisticsResponse], error)
}

// NewDuckAPIClient constructs a client for the apiService.DuckAPI service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDuckAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DuckAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	duckAPIMethods := api.File_api_proto.Services().ByName("DuckAPI").Methods()
	return &duckAPIClient{
		startRun: connect.NewClient[api.StartRunRequest, api.StartRunResponse](
			httpClient,
			baseURL+DuckAPIStartRunProcedure,
			connect.WithSchema(duckAPIMethods.ByName("StartRun")),
			connect.WithClientOptions(opts...),
		),
		stopRun: connect.NewClient[api.StopRunRequest, api.StopRunResponse](
			httpClient,
			baseURL+DuckAPIStopRunProcedure,
			connect.WithSchema(duckAPIMethods.ByName("StopRun")),
			connect.WithClientOptions(opts...),
		),
		forceStopRun: connect.NewClient[api.ForceStopRunRequest, api.ForceStopRunResponse](
			httpClient,
			baseURL+DuckAPIForceStopRunProcedure,
			connect.WithSchema(duckAPIMethods.ByName("ForceStopRun")),
			connect.WithClientOptions(opts...),
		),
		getProcessStates: connect.NewClient[api.GetProcessStatesRequest, api.GetProcessStatesResponse](
			httpClient,
			baseURL+DuckAPIGetProcessStatesProcedure,
			connect.WithSchema(duckAPIMethods.ByName("GetProcessStates")),
			connect.WithClientOptions(opts...),
		),
		restartServices: connect.NewClient[api.RestartServicesRequest, api.RestartServicesResponse](
			httpClient,
			baseURL+DuckAPIRestartServicesProcedure,
			connect.WithSchema(duckAPIMethods.ByName("RestartServices")),
			connect.WithClientOptions(opts...),
		),
		createGDC: connect.NewClient[api.CreateGDCRequest, api.CreateGDCResponse](
			httpClient,
			baseURL+DuckAPICreateGDCProcedure,
			connect.WithSchema(duckAPIMethods.ByName("CreateGDC")),
			connect.WithClientOptions(opts...),
		),
		getGDCs: connect.NewClient[api.GetGDCsRequest, api.GetGDCsResponse](
			httpClient,
			baseURL+DuckAPIGetGDCsProcedure,
			connect.WithSchema(duckAPIMethods.ByName("GetGDCs")),
			connect.WithClientOptions(opts...),
		),
		getGDC: connect.NewClient[api.GetGDCRequest, api.GetGDCResponse](
			httpClient,
			baseURL+DuckAPIGetGDCProcedure,
			connect.WithSchema(duckAPIMethods.ByName("GetGDC")),
			connect.WithClientOptions(opts...),
		),
		updateGDC: connect.NewClient[api.UpdateGDCRequest, api.UpdateGDCResponse](
			httpClient,
			baseURL+DuckAPIUpdateGDCProcedure,
			connect.WithSchema(duckAPIMethods.ByName("UpdateGDC")),
			connect.WithClientOptions(opts...),
		),
		deleteGDC: connect.NewClient[api.DeleteGDCRequest, api.DeleteGDCResponse](
			httpClient,
			baseURL+DuckAPIDeleteGDCProcedure,
			connect.WithSchema(duckAPIMethods.ByName("DeleteGDC")),
			connect.WithClientOptions(opts...),
		),
		createLDC: connect.NewClient[api.CreateLDCRequest, api.CreateLDCResponse](
			httpClient,
			baseURL+DuckAPICreateLDCProcedure,
			connect.WithSchema(duckAPIMethods.ByName("CreateLDC")),
			connect.WithClientOptions(opts...),
		),
		getLDCs: connect.NewClient[api.GetLDCsRequest, api.GetLDCsResponse](
			httpClient,
			baseURL+DuckAPIGetLDCsProcedure,
			connect.WithSchema(duckAPIMethods.ByName("GetLDCs")),
			connect.WithClientOptions(opts...),
		),
		getLDC: connect.NewClient[api.GetLDCRequest, api.GetLDCResponse](
			httpClient,
			baseURL+DuckAPIGetLDCProcedure,
			connect.WithSchema(duckAPIMethods.ByName("GetLDC")),
			connect.WithClientOptions(opts...),
		),
		updateLDC: connect.NewClient[api.UpdateLDCRequest, api.UpdateLDCResponse](
			httpClient,
			baseURL+DuckAPIUpdateLDCProcedure,
			connect.WithSchema(duckAPIMethods.ByName("UpdateLDC")),
			connect.WithClientOptions(opts...),
		),
		deleteLDC: connect.NewClient[api.DeleteLDCRequest, api.DeleteLDCResponse](
			httpClient,
			baseURL+DuckAPIDeleteLDCProcedure,
			connect.WithSchema(duckAPIMethods.ByName("DeleteLDC")),
			connect.WithClientOptions(opts...),
		),
		createEquipment: connect.NewClient[api.CreateEquipmentRequest, api.CreateEquipmentResponse](
			httpClient,
			baseURL+DuckAPICreateEquipmentProcedure,
			connect.WithSchema(duckAPIMethods.ByName("CreateEquipment")),
			connect.WithClientOptions(opts...),
		),
		getEquipments: connect.NewClient[api.GetEquipmentsRequest, api.GetEquipmentsResponse](
			httpClient,
			baseURL+DuckAPIGetEquipmentsProcedure,
			connect.WithSchema(duckAPIMethods.ByName("GetEquipments")),
			connect.WithClientOptions(opts...),
		),
		getEquipment: connect.NewClient[api.GetEquipmentRequest, api.GetEquipmentResponse](
			httpClient,
			baseURL+DuckAPIGetEquipmentProcedure,
			connect.WithSchema(duckAPIMethods.ByName("GetEquipment")),
			connect.WithClientOptions(opts...),
		),
		updateEquipment: connect.NewClient[api.UpdateEquipmentRequest, api.UpdateEquipmentResponse](
			httpClient,
			baseURL+DuckAPIUpdateEquipmentProcedure,
			connect.WithSchema(duckAPIMethods.ByName("UpdateEquipment")),
			connect.WithClientOptions(opts...),
		),
		deleteEquipment: connect.NewClient[api.DeleteEquipmentRequest, api.DeleteEquipmentResponse](
			httpClient,
			baseURL+DuckAPIDeleteEquipmentProcedure,
			connect.WithSchema(duckAPIMethods.ByName("DeleteEquipment")),
			connect.WithClientOptions(opts...),
		),
		getDecoderConfiguration: connect.NewClient[api.GetDecoderConfigurationRequest, api.GetDecoderConfigurationResponse](
			httpClient,
			baseURL+DuckAPIGetDecoderConfigurationProcedure,
			connect.WithSchema(duckAPIMethods.ByName("GetDecoderConfiguration")),
			connect.WithClientOptions(opts...),
		),
		updateDecoderConfiguration: connect.NewClient[api.UpdateDecoderConfigurationRequest, api.UpdateDecoderConfigurationResponse](
			httpClient,
			baseURL+DuckAPIUpdateDecoderConfigurationProcedure,
			connect.WithSchema(duckAPIMethods.ByName("UpdateDecoderConfiguration")),
			connect.WithClientOptions(opts...),
		),
		getRunNumber: connect.NewClient[api.GetRunNumberRequest, api.GetRunNumberResponse](
			httpClient,
			baseURL+DuckAPIGetRunNumberProcedure,
			connect.WithSchema(duckAPIMethods.ByName("GetRunNumber")),
			connect.WithClientOptions(opts...),
		),
		checkDisabled: connect.NewClient[api.CheckDisabledRequest, api.CheckDisabledResponse](
			httpClient,
			baseURL+DuckAPICheckDisabledProcedure,
			connect.WithSchema(duckAPIMethods.ByName("CheckDisabled")),
			connect.WithClientOptions(opts...),
		),
		getToken: connect.NewClient[api.GetTokenRequest, api.GetTokenResponse](
			httpClient,
			baseURL+DuckAPIGetTokenProcedure,
			connect.WithSchema(duckAPIMethods.ByName("GetToken")),
			connect.WithClientOptions(opts...),
		),
		startTestDevices: connect.NewClient[api.StartTestDevicesRequest, api.StartTestDevicesResponse](
			httpClient,
			baseURL+DuckAPIStartTestDevicesProcedure,
			connect.WithSchema(duckAPIMethods.ByName("StartTestDevices")),
			connect.WithClientOptions(opts...),
		),
		stopTestDevices: connect.NewClient[api.StopTestDevicesRequest, api.StopTestDevicesResponse](
			httpClient,
			baseURL+DuckAPIStopTestDevicesProcedure,
			connect.WithSchema(duckAPIMethods.ByName("StopTestDevices")),
			connect.WithClientOptions(opts...),
		),
		getTestDevicesStates: connect.NewClient[api.GetTestDevicesStatesRequest, api.GetTestDevicesStatesResponse](
			httpClient,
			baseURL+DuckAPIGetTestDevicesStatesProcedure,
			connect.WithSchema(duckAPIMethods.ByName("GetTestDevicesStates")),
			connect.WithClientOptions(opts...),
		),
		listTestDevices: connect.NewClient[api.ListTestDevicesRequest, api.ListTestDevicesResponse](
			httpClient,
			baseURL+DuckAPIListTestDevicesProcedure,
			connect.WithSchema(duckAPIMethods.ByName("ListTestDevices")),
			connect.WithClientOptions(opts...),
		),
		getTestDeviceStatistics: connect.NewClient[api.GetTestDeviceStatisticsRequest, api.GetTestDeviceStatisticsResponse](
			httpClient,
			baseURL+DuckAPIGetTestDeviceStatisticsProcedure,
			connect.WithSchema(duckAPIMethods.ByName("GetTestDeviceStatistics")),
			connect.WithClientOptions(opts...),
		),
	}
}

// duckAPIClient implements DuckAPIClient.
type duckAPIClient struct {
	startRun                   *connect.Client[api.StartRunRequest, api.StartRunResponse]
	stopRun                    *connect.Client[api.StopRunRequest, api.StopRunResponse]
	forceStopRun               *connect.Client[api.ForceStopRunRequest, api.ForceStopRunResponse]
	getProcessStates           *connect.Client[api.GetProcessStatesRequest, api.GetProcessStatesResponse]
	restartServices            *connect.Client[api.RestartServicesRequest, api.RestartServicesResponse]
	createGDC                  *connect.Client[api.CreateGDCRequest, api.CreateGDCResponse]
	getGDCs                    *connect.Client[api.GetGDCsRequest, api.GetGDCsResponse]
	getGDC                     *connect.Client[api.GetGDCRequest, api.GetGDCResponse]
	updateGDC                  *connect.Client[api.UpdateGDCRequest, api.UpdateGDCResponse]
	deleteGDC                  *connect.Client[api.DeleteGDCRequest, api.DeleteGDCResponse]
	createLDC                  *connect.Client[api.CreateLDCRequest, api.CreateLDCResponse]
	getLDCs                    *connect.Client[api.GetLDCsRequest, api.GetLDCsResponse]
	getLDC                     *connect.Client[api.GetLDCRequest, api.GetLDCResponse]
	updateLDC                  *connect.Client[api.UpdateLDCRequest, api.UpdateLDCResponse]
	deleteLDC                  *connect.Client[api.DeleteLDCRequest, api.DeleteLDCResponse]
	createEquipment            *connect.Client[api.CreateEquipmentRequest, api.CreateEquipmentResponse]
	getEquipments              *connect.Client[api.GetEquipmentsRequest, api.GetEquipmentsResponse]
	getEquipment               *connect.Client[api.GetEquipmentRequest, api.GetEquipmentResponse]
	updateEquipment            *connect.Client[api.UpdateEquipmentRequest, api.UpdateEquipmentResponse]
	deleteEquipment            *connect.Client[api.DeleteEquipmentRequest, api.DeleteEquipmentResponse]
	getDecoderConfiguration    *connect.Client[api.GetDecoderConfigurationRequest, api.GetDecoderConfigurationResponse]
	updateDecoderConfiguration *connect.Client[api.UpdateDecoderConfigurationRequest, api.UpdateDecoderConfigurationResponse]
	getRunNumber               *connect.Client[api.GetRunNumberRequest, api.GetRunNumberResponse]
	checkDisabled              *connect.Client[api.CheckDisabledRequest, api.CheckDisabledResponse]
	getToken                   *connect.Client[api.GetTokenRequest, api.GetTokenResponse]
	startTestDevices           *connect.Client[api.StartTestDevicesRequest, api.StartTestDevicesResponse]
	stopTestDevices            *connect.Client[api.StopTestDevicesRequest, api.StopTestDevicesResponse]
	getTestDevicesStates       *connect.Client[api.GetTestDevicesStatesRequest, api.GetTestDevicesStatesResponse]
	listTestDevices            *connect.Client[api.ListTestDevicesRequest, api.ListTestDevicesResponse]
	getTestDeviceStatistics    *connect.Client[api.GetTestDeviceStatisticsRequest, api.GetTestDeviceStatisticsResponse]
}

// StartRun calls apiService.DuckAPI.StartRun.
func (c *duckAPIClient) StartRun(ctx context.Context, req *connect.Request[api.StartRunRequest]) (*connect.Response[api.StartRunResponse], error) {
	return c.startRun.CallUnary(ctx, req)
}

// StopRun calls apiService.DuckAPI.StopRun.
func (c *duckAPIClient) StopRun(ctx context.Context, req *connect.Request[api.StopRunRequest]) (*connect.Response[api.StopRunResponse], error) {
	return c.stopRun.CallUnary(ctx, req)
}

// ForceStopRun calls apiService.DuckAPI.ForceStopRun.
func (c *duckAPIClient) ForceStopRun(ctx context.Context, req *connect.Request[api.ForceStopRunRequest]) (*connect.Response[api.ForceStopRunResponse], error) {
	return c.forceStopRun.CallUnary(ctx, req)
}

// GetProcessStates calls apiService.DuckAPI.GetProcessStates.
func (c *duckAPIClient) GetProcessStates(ctx context.Context, req *connect.Request[api.GetProcessStatesRequest]) (*connect.Response[api.GetProcessStatesResponse], error) {
	return c.getProcessStates.CallUnary(ctx, req)
}

// RestartServices calls apiService.DuckAPI.RestartServices.
func (c *duckAPIClient) RestartServices(ctx context.Context, req *connect.Request[api.RestartServicesRequest]) (*connect.Response[api.RestartServicesResponse], error) {
	return c.restartServices.CallUnary(ctx, req)
}

// CreateGDC calls apiService.DuckAPI.CreateGDC.
func (c *duckAPIClient) CreateGDC(ctx context.Context, req *connect.Request[api.CreateGDCRequest]) (*connect.Response[api.CreateGDCResponse], error) {
	return c.createGDC.CallUnary(ctx, req)
}

// GetGDCs calls apiService.DuckAPI.GetGDCs.
func (c *duckAPIClient) GetGDCs(ctx context.Context, req *connect.Request[api.GetGDCsRequest]) (*connect.Response[api.GetGDCsResponse], error) {
	return c.getGDCs.CallUnary(ctx, req)
}

// GetGDC calls apiService.DuckAPI.GetGDC.
func (c *duckAPIClient) GetGDC(ctx context.Context, req *connect.Request[api.GetGDCRequest]) (*connect.Response[api.GetGDCResponse], error) {
	return c.getGDC.CallUnary(ctx, req)
}

// UpdateGDC calls apiService.DuckAPI.UpdateGDC.
func (c *duckAPIClient) UpdateGDC(ctx context.Context, req *connect.Request[api.UpdateGDCRequest]) (*connect.Response[api.UpdateGDCResponse], error) {
	return c.updateGDC.CallUnary(ctx, req)
}

// DeleteGDC calls apiService.DuckAPI.DeleteGDC.
func (c *duckAPIClient) DeleteGDC(ctx context.Context, req *connect.Request[api.DeleteGDCRequest]) (*connect.Response[api.DeleteGDCResponse], error) {
	return c.deleteGDC.CallUnary(ctx, req)
}

// CreateLDC calls apiService.DuckAPI.CreateLDC.
func (c *duckAPIClient) CreateLDC(ctx context.Context, req *connect.Request[api.CreateLDCRequest]) (*connect.Response[api.CreateLDCResponse], error) {
	return c.createLDC.CallUnary(ctx, req)
}

// GetLDCs calls apiService.DuckAPI.GetLDCs.
func (c *duckAPIClient) GetLDCs(ctx context.Context, req *connect.Request[api.GetLDCsRequest]) (*connect.Response[api.GetLDCsResponse], error) {
	return c.getLDCs.CallUnary(ctx, req)
}

// GetLDC calls apiService.DuckAPI.GetLDC.
func (c *duckAPIClient) GetLDC(ctx context.Context, req *connect.Request[api.GetLDCRequest]) (*connect.Response[api.GetLDCResponse], error) {
	return c.getLDC.CallUnary(ctx, req)
}

// UpdateLDC calls apiService.DuckAPI.UpdateLDC.
func (c *duckAPIClient) UpdateLDC(ctx context.Context, req *connect.Request[api.UpdateLDCRequest]) (*connect.Response[api.UpdateLDCResponse], error) {
	return c.updateLDC.CallUnary(ctx, req)
}

// DeleteLDC calls apiService.DuckAPI.DeleteLDC.
func (c *duckAPIClient) DeleteLDC(ctx context.Context, req *connect.Request[api.DeleteLDCRequest]) (*connect.Response[api.DeleteLDCResponse], error) {
	return c.deleteLDC.CallUnary(ctx, req)
}

// CreateEquipment calls apiService.DuckAPI.CreateEquipment.
func (c *duckAPIClient) CreateEquipment(ctx context.Context, req *connect.Request[api.CreateEquipmentRequest]) (*connect.Response[api.CreateEquipmentResponse], error) {
	return c.createEquipment.CallUnary(ctx, req)
}

// GetEquipments calls apiService.DuckAPI.GetEquipments.
func (c *duckAPIClient) GetEquipments(ctx context.Context, req *connect.Request[api.GetEquipmentsRequest]) (*connect.Response[api.GetEquipmentsResponse], error) {
	return c.getEquipments.CallUnary(ctx, req)
}

// GetEquipment calls apiService.DuckAPI.GetEquipment.
func (c *duckAPIClient) GetEquipment(ctx context.Context, req *connect.Request[api.GetEquipmentRequest]) (*connect.Response[api.GetEquipmentResponse], error) {
	return c.getEquipment.CallUnary(ctx, req)
}

// UpdateEquipment calls apiService.DuckAPI.UpdateEquipment.
func (c *duckAPIClient) UpdateEquipment(ctx context.Context, req *connect.Request[api.UpdateEquipmentRequest]) (*connect.Response[api.UpdateEquipmentResponse], error) {
	return c.updateEquipment.CallUnary(ctx, req)
}

// DeleteEquipment calls apiService.DuckAPI.DeleteEquipment.
func (c *duckAPIClient) DeleteEquipment(ctx context.Context, req *connect.Request[api.DeleteEquipmentRequest]) (*connect.Response[api.DeleteEquipmentResponse], error) {
	return c.deleteEquipment.CallUnary(ctx, req)
}

// GetDecoderConfiguration calls apiService.DuckAPI.GetDecoderConfiguration.
func (c *duckAPIClient) GetDecoderConfiguration(ctx context.Context, req *connect.Request[api.GetDecoderConfigurationRequest]) (*connect.Response[api.GetDecoderConfigurationResponse], error) {
	return c.getDecoderConfiguration.CallUnary(ctx, req)
}

// UpdateDecoderConfiguration calls apiService.DuckAPI.UpdateDecoderConfiguration.
func (c *duckAPIClient) UpdateDecoderConfiguration(ctx context.Context, req *connect.Request[api.UpdateDecoderConfigurationRequest]) (*connect.Response[api.UpdateDecoderConfigurationResponse], error) {
	return c.updateDecoderConfiguration.CallUnary(ctx, req)
}

// GetRunNumber calls apiService.DuckAPI.GetRunNumber.
func (c *duckAPIClient) GetRunNumber(ctx context.Context, req *connect.Request[api.GetRunNumberRequest]) (*connect.Response[api.GetRunNumberResponse], error) {
	return c.getRunNumber.CallUnary(ctx, req)
}

// CheckDisabled calls apiService.DuckAPI.CheckDisabled.
func (c *duckAPIClient) CheckDisabled(ctx context.Context, req *connect.Request[api.CheckDisabledRequest]) (*connect.Response[api.CheckDisabledResponse], error) {
	return c.checkDisabled.CallUnary(ctx, req)
}

// GetToken calls apiService.DuckAPI.GetToken.
func (c *duckAPIClient) GetToken(ctx context.Context, req *connect.Request[api.GetTokenRequest]) (*connect.Response[api.GetTokenResponse], error) {
	return c.getToken.CallUnary(ctx, req)
}

// StartTestDevices calls apiService.DuckAPI.StartTestDevices.
func (c *duckAPIClient) StartTestDevices(ctx context.Context, req *connect.Request[api.StartTestDevicesRequest]) (*connect.Response[api.StartTestDevicesResponse], error) {
	return c.startTestDevices.CallUnary(ctx, req)
}

// StopTestDevices calls apiService.DuckAPI.StopTestDevices.
func (c *duckAPIClient) StopTestDevices(ctx context.Context, req *connect.Request[api.StopTestDevicesRequest]) (*connect.Response[api.StopTestDevicesResponse], error) {
	return c.stopTestDevices.CallUnary(ctx, req)
}

// GetTestDevicesStates calls apiService.DuckAPI.GetTestDevicesStates.
func (c *duckAPIClient) GetTestDevicesStates(ctx context.Context, req *connect.Request[api.GetTestDevicesStatesRequest]) (*connect.Response[api.GetTestDevicesStatesResponse], error) {
	return c.getTestDevicesStates.CallUnary(ctx, req)
}

// ListTestDevices calls apiService.DuckAPI.ListTestDevices.
func (c *duckAPIClient) ListTestDevices(ctx context.Context, req *connect.Request[api.ListTestDevicesRequest]) (*connect.Response[api.ListTestDevicesResponse], error) {
	return c.listTestDevices.CallUnary(ctx, req)
}

// GetTestDeviceStatistics calls apiService.DuckAPI.GetTestDeviceStatistics.
func (c *duckAPIClient) GetTestDeviceStatistics(ctx context.Context, req *connect.Request[api.GetTestDeviceStatisticsRequest]) (*connect.Response[api.GetTestDeviceStatisticsResponse], error) {
	return c.getTestDeviceStatistics.CallUnary(ctx, req)
}

// DuckAPIHandler is an implementation of the apiService.DuckAPI service.
type DuckAPIHandler interface {
	// Run Control Operations
	StartRun(context.Context, *connect.Request[api.StartRunRequest]) (*connect.Response[api.StartRunResponse], error)
	StopRun(context.Context, *connect.Request[api.StopRunRequest]) (*connect.Response[api.StopRunResponse], error)
	ForceStopRun(context.Context, *connect.Request[api.ForceStopRunRequest]) (*connect.Response[api.ForceStopRunResponse], error)
	GetProcessStates(context.Context, *connect.Request[api.GetProcessStatesRequest]) (*connect.Response[api.GetProcessStatesResponse], error)
	RestartServices(context.Context, *connect.Request[api.RestartServicesRequest]) (*connect.Response[api.RestartServicesResponse], error)
	// GDC Management
	CreateGDC(context.Context, *connect.Request[api.CreateGDCRequest]) (*connect.Response[api.CreateGDCResponse], error)
	GetGDCs(context.Context, *connect.Request[api.GetGDCsRequest]) (*connect.Response[api.GetGDCsResponse], error)
	GetGDC(context.Context, *connect.Request[api.GetGDCRequest]) (*connect.Response[api.GetGDCResponse], error)
	UpdateGDC(context.Context, *connect.Request[api.UpdateGDCRequest]) (*connect.Response[api.UpdateGDCResponse], error)
	DeleteGDC(context.Context, *connect.Request[api.DeleteGDCRequest]) (*connect.Response[api.DeleteGDCResponse], error)
	// LDC Management
	CreateLDC(context.Context, *connect.Request[api.CreateLDCRequest]) (*connect.Response[api.CreateLDCResponse], error)
	GetLDCs(context.Context, *connect.Request[api.GetLDCsRequest]) (*connect.Response[api.GetLDCsResponse], error)
	GetLDC(context.Context, *connect.Request[api.GetLDCRequest]) (*connect.Response[api.GetLDCResponse], error)
	UpdateLDC(context.Context, *connect.Request[api.UpdateLDCRequest]) (*connect.Response[api.UpdateLDCResponse], error)
	DeleteLDC(context.Context, *connect.Request[api.DeleteLDCRequest]) (*connect.Response[api.DeleteLDCResponse], error)
	// Equipment Management
	CreateEquipment(context.Context, *connect.Request[api.CreateEquipmentRequest]) (*connect.Response[api.CreateEquipmentResponse], error)
	GetEquipments(context.Context, *connect.Request[api.GetEquipmentsRequest]) (*connect.Response[api.GetEquipmentsResponse], error)
	GetEquipment(context.Context, *connect.Request[api.GetEquipmentRequest]) (*connect.Response[api.GetEquipmentResponse], error)
	UpdateEquipment(context.Context, *connect.Request[api.UpdateEquipmentRequest]) (*connect.Response[api.UpdateEquipmentResponse], error)
	DeleteEquipment(context.Context, *connect.Request[api.DeleteEquipmentRequest]) (*connect.Response[api.DeleteEquipmentResponse], error)
	// Decoder Configuration
	GetDecoderConfiguration(context.Context, *connect.Request[api.GetDecoderConfigurationRequest]) (*connect.Response[api.GetDecoderConfigurationResponse], error)
	UpdateDecoderConfiguration(context.Context, *connect.Request[api.UpdateDecoderConfigurationRequest]) (*connect.Response[api.UpdateDecoderConfigurationResponse], error)
	// Run Information
	GetRunNumber(context.Context, *connect.Request[api.GetRunNumberRequest]) (*connect.Response[api.GetRunNumberResponse], error)
	CheckDisabled(context.Context, *connect.Request[api.CheckDisabledRequest]) (*connect.Response[api.CheckDisabledResponse], error)
	// Authentication
	GetToken(context.Context, *connect.Request[api.GetTokenRequest]) (*connect.Response[api.GetTokenResponse], error)
	// Test Device Management
	StartTestDevices(context.Context, *connect.Request[api.StartTestDevicesRequest]) (*connect.Response[api.StartTestDevicesResponse], error)
	StopTestDevices(context.Context, *connect.Request[api.StopTestDevicesRequest]) (*connect.Response[api.StopTestDevicesResponse], error)
	GetTestDevicesStates(context.Context, *connect.Request[api.GetTestDevicesStatesRequest]) (*connect.Response[api.GetTestDevicesStatesResponse], error)
	ListTestDevices(context.Context, *connect.Request[api.ListTestDevicesRequest]) (*connect.Response[api.ListTestDevicesResponse], error)
	GetTestDeviceStatistics(context.Context, *connect.Request[api.GetTestDeviceStatisticsRequest]) (*connect.Response[api.GetTestDeviceStatisticsResponse], error)
}

// NewDuckAPIHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDuckAPIHandler(svc DuckAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	duckAPIMethods := api.File_api_proto.Services().ByName("DuckAPI").Methods()
	duckAPIStartRunHandler := connect.NewUnaryHandler(
		DuckAPIStartRunProcedure,
		svc.StartRun,
		connect.WithSchema(duckAPIMethods.ByName("StartRun")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIStopRunHandler := connect.NewUnaryHandler(
		DuckAPIStopRunProcedure,
		svc.StopRun,
		connect.WithSchema(duckAPIMethods.ByName("StopRun")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIForceStopRunHandler := connect.NewUnaryHandler(
		DuckAPIForceStopRunProcedure,
		svc.ForceStopRun,
		connect.WithSchema(duckAPIMethods.ByName("ForceStopRun")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIGetProcessStatesHandler := connect.NewUnaryHandler(
		DuckAPIGetProcessStatesProcedure,
		svc.GetProcessStates,
		connect.WithSchema(duckAPIMethods.ByName("GetProcessStates")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIRestartServicesHandler := connect.NewUnaryHandler(
		DuckAPIRestartServicesProcedure,
		svc.RestartServices,
		connect.WithSchema(duckAPIMethods.ByName("RestartServices")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPICreateGDCHandler := connect.NewUnaryHandler(
		DuckAPICreateGDCProcedure,
		svc.CreateGDC,
		connect.WithSchema(duckAPIMethods.ByName("CreateGDC")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIGetGDCsHandler := connect.NewUnaryHandler(
		DuckAPIGetGDCsProcedure,
		svc.GetGDCs,
		connect.WithSchema(duckAPIMethods.ByName("GetGDCs")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIGetGDCHandler := connect.NewUnaryHandler(
		DuckAPIGetGDCProcedure,
		svc.GetGDC,
		connect.WithSchema(duckAPIMethods.ByName("GetGDC")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIUpdateGDCHandler := connect.NewUnaryHandler(
		DuckAPIUpdateGDCProcedure,
		svc.UpdateGDC,
		connect.WithSchema(duckAPIMethods.ByName("UpdateGDC")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIDeleteGDCHandler := connect.NewUnaryHandler(
		DuckAPIDeleteGDCProcedure,
		svc.DeleteGDC,
		connect.WithSchema(duckAPIMethods.ByName("DeleteGDC")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPICreateLDCHandler := connect.NewUnaryHandler(
		DuckAPICreateLDCProcedure,
		svc.CreateLDC,
		connect.WithSchema(duckAPIMethods.ByName("CreateLDC")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIGetLDCsHandler := connect.NewUnaryHandler(
		DuckAPIGetLDCsProcedure,
		svc.GetLDCs,
		connect.WithSchema(duckAPIMethods.ByName("GetLDCs")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIGetLDCHandler := connect.NewUnaryHandler(
		DuckAPIGetLDCProcedure,
		svc.GetLDC,
		connect.WithSchema(duckAPIMethods.ByName("GetLDC")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIUpdateLDCHandler := connect.NewUnaryHandler(
		DuckAPIUpdateLDCProcedure,
		svc.UpdateLDC,
		connect.WithSchema(duckAPIMethods.ByName("UpdateLDC")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIDeleteLDCHandler := connect.NewUnaryHandler(
		DuckAPIDeleteLDCProcedure,
		svc.DeleteLDC,
		connect.WithSchema(duckAPIMethods.ByName("DeleteLDC")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPICreateEquipmentHandler := connect.NewUnaryHandler(
		DuckAPICreateEquipmentProcedure,
		svc.CreateEquipment,
		connect.WithSchema(duckAPIMethods.ByName("CreateEquipment")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIGetEquipmentsHandler := connect.NewUnaryHandler(
		DuckAPIGetEquipmentsProcedure,
		svc.GetEquipments,
		connect.WithSchema(duckAPIMethods.ByName("GetEquipments")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIGetEquipmentHandler := connect.NewUnaryHandler(
		DuckAPIGetEquipmentProcedure,
		svc.GetEquipment,
		connect.WithSchema(duckAPIMethods.ByName("GetEquipment")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIUpdateEquipmentHandler := connect.NewUnaryHandler(
		DuckAPIUpdateEquipmentProcedure,
		svc.UpdateEquipment,
		connect.WithSchema(duckAPIMethods.ByName("UpdateEquipment")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIDeleteEquipmentHandler := connect.NewUnaryHandler(
		DuckAPIDeleteEquipmentProcedure,
		svc.DeleteEquipment,
		connect.WithSchema(duckAPIMethods.ByName("DeleteEquipment")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIGetDecoderConfigurationHandler := connect.NewUnaryHandler(
		DuckAPIGetDecoderConfigurationProcedure,
		svc.GetDecoderConfiguration,
		connect.WithSchema(duckAPIMethods.ByName("GetDecoderConfiguration")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIUpdateDecoderConfigurationHandler := connect.NewUnaryHandler(
		DuckAPIUpdateDecoderConfigurationProcedure,
		svc.UpdateDecoderConfiguration,
		connect.WithSchema(duckAPIMethods.ByName("UpdateDecoderConfiguration")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIGetRunNumberHandler := connect.NewUnaryHandler(
		DuckAPIGetRunNumberProcedure,
		svc.GetRunNumber,
		connect.WithSchema(duckAPIMethods.ByName("GetRunNumber")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPICheckDisabledHandler := connect.NewUnaryHandler(
		DuckAPICheckDisabledProcedure,
		svc.CheckDisabled,
		connect.WithSchema(duckAPIMethods.ByName("CheckDisabled")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIGetTokenHandler := connect.NewUnaryHandler(
		DuckAPIGetTokenProcedure,
		svc.GetToken,
		connect.WithSchema(duckAPIMethods.ByName("GetToken")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIStartTestDevicesHandler := connect.NewUnaryHandler(
		DuckAPIStartTestDevicesProcedure,
		svc.StartTestDevices,
		connect.WithSchema(duckAPIMethods.ByName("StartTestDevices")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIStopTestDevicesHandler := connect.NewUnaryHandler(
		DuckAPIStopTestDevicesProcedure,
		svc.StopTestDevices,
		connect.WithSchema(duckAPIMethods.ByName("StopTestDevices")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIGetTestDevicesStatesHandler := connect.NewUnaryHandler(
		DuckAPIGetTestDevicesStatesProcedure,
		svc.GetTestDevicesStates,
		connect.WithSchema(duckAPIMethods.ByName("GetTestDevicesStates")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIListTestDevicesHandler := connect.NewUnaryHandler(
		DuckAPIListTestDevicesProcedure,
		svc.ListTestDevices,
		connect.WithSchema(duckAPIMethods.ByName("ListTestDevices")),
		connect.WithHandlerOptions(opts...),
	)
	duckAPIGetTestDeviceStatisticsHandler := connect.NewUnaryHandler(
		DuckAPIGetTestDeviceStatisticsProcedure,
		svc.GetTestDeviceStatistics,
		connect.WithSchema(duckAPIMethods.ByName("GetTestDeviceStatistics")),
		connect.WithHandlerOptions(opts...),
	)
	return "/apiService.DuckAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DuckAPIStartRunProcedure:
			duckAPIStartRunHandler.ServeHTTP(w, r)
		case DuckAPIStopRunProcedure:
			duckAPIStopRunHandler.ServeHTTP(w, r)
		case DuckAPIForceStopRunProcedure:
			duckAPIForceStopRunHandler.ServeHTTP(w, r)
		case DuckAPIGetProcessStatesProcedure:
			duckAPIGetProcessStatesHandler.ServeHTTP(w, r)
		case DuckAPIRestartServicesProcedure:
			duckAPIRestartServicesHandler.ServeHTTP(w, r)
		case DuckAPICreateGDCProcedure:
			duckAPICreateGDCHandler.ServeHTTP(w, r)
		case DuckAPIGetGDCsProcedure:
			duckAPIGetGDCsHandler.ServeHTTP(w, r)
		case DuckAPIGetGDCProcedure:
			duckAPIGetGDCHandler.ServeHTTP(w, r)
		case DuckAPIUpdateGDCProcedure:
			duckAPIUpdateGDCHandler.ServeHTTP(w, r)
		case DuckAPIDeleteGDCProcedure:
			duckAPIDeleteGDCHandler.ServeHTTP(w, r)
		case DuckAPICreateLDCProcedure:
			duckAPICreateLDCHandler.ServeHTTP(w, r)
		case DuckAPIGetLDCsProcedure:
			duckAPIGetLDCsHandler.ServeHTTP(w, r)
		case DuckAPIGetLDCProcedure:
			duckAPIGetLDCHandler.ServeHTTP(w, r)
		case DuckAPIUpdateLDCProcedure:
			duckAPIUpdateLDCHandler.ServeHTTP(w, r)
		case DuckAPIDeleteLDCProcedure:
			duckAPIDeleteLDCHandler.ServeHTTP(w, r)
		case DuckAPICreateEquipmentProcedure:
			duckAPICreateEquipmentHandler.ServeHTTP(w, r)
		case DuckAPIGetEquipmentsProcedure:
			duckAPIGetEquipmentsHandler.ServeHTTP(w, r)
		case DuckAPIGetEquipmentProcedure:
			duckAPIGetEquipmentHandler.ServeHTTP(w, r)
		case DuckAPIUpdateEquipmentProcedure:
			duckAPIUpdateEquipmentHandler.ServeHTTP(w, r)
		case DuckAPIDeleteEquipmentProcedure:
			duckAPIDeleteEquipmentHandler.ServeHTTP(w, r)
		case DuckAPIGetDecoderConfigurationProcedure:
			duckAPIGetDecoderConfigurationHandler.ServeHTTP(w, r)
		case DuckAPIUpdateDecoderConfigurationProcedure:
			duckAPIUpdateDecoderConfigurationHandler.ServeHTTP(w, r)
		case DuckAPIGetRunNumberProcedure:
			duckAPIGetRunNumberHandler.ServeHTTP(w, r)
		case DuckAPICheckDisabledProcedure:
			duckAPICheckDisabledHandler.ServeHTTP(w, r)
		case DuckAPIGetTokenProcedure:
			duckAPIGetTokenHandler.ServeHTTP(w, r)
		case DuckAPIStartTestDevicesProcedure:
			duckAPIStartTestDevicesHandler.ServeHTTP(w, r)
		case DuckAPIStopTestDevicesProcedure:
			duckAPIStopTestDevicesHandler.ServeHTTP(w, r)
		case DuckAPIGetTestDevicesStatesProcedure:
			duckAPIGetTestDevicesStatesHandler.ServeHTTP(w, r)
		case DuckAPIListTestDevicesProcedure:
			duckAPIListTestDevicesHandler.ServeHTTP(w, r)
		case DuckAPIGetTestDeviceStatisticsProcedure:
			duckAPIGetTestDeviceStatisticsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDuckAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedDuckAPIHandler struct{}

func (UnimplementedDuckAPIHandler) StartRun(context.Context, *connect.Request[api.StartRunRequest]) (*connect.Response[api.StartRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.StartRun is not implemented"))
}

func (UnimplementedDuckAPIHandler) StopRun(context.Context, *connect.Request[api.StopRunRequest]) (*connect.Response[api.StopRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.StopRun is not implemented"))
}

func (UnimplementedDuckAPIHandler) ForceStopRun(context.Context, *connect.Request[api.ForceStopRunRequest]) (*connect.Response[api.ForceStopRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.ForceStopRun is not implemented"))
}

func (UnimplementedDuckAPIHandler) GetProcessStates(context.Context, *connect.Request[api.GetProcessStatesRequest]) (*connect.Response[api.GetProcessStatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.GetProcessStates is not implemented"))
}

func (UnimplementedDuckAPIHandler) RestartServices(context.Context, *connect.Request[api.RestartServicesRequest]) (*connect.Response[api.RestartServicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.RestartServices is not implemented"))
}

func (UnimplementedDuckAPIHandler) CreateGDC(context.Context, *connect.Request[api.CreateGDCRequest]) (*connect.Response[api.CreateGDCResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.CreateGDC is not implemented"))
}

func (UnimplementedDuckAPIHandler) GetGDCs(context.Context, *connect.Request[api.GetGDCsRequest]) (*connect.Response[api.GetGDCsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.GetGDCs is not implemented"))
}

func (UnimplementedDuckAPIHandler) GetGDC(context.Context, *connect.Request[api.GetGDCRequest]) (*connect.Response[api.GetGDCResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.GetGDC is not implemented"))
}

func (UnimplementedDuckAPIHandler) UpdateGDC(context.Context, *connect.Request[api.UpdateGDCRequest]) (*connect.Response[api.UpdateGDCResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.UpdateGDC is not implemented"))
}

func (UnimplementedDuckAPIHandler) DeleteGDC(context.Context, *connect.Request[api.DeleteGDCRequest]) (*connect.Response[api.DeleteGDCResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.DeleteGDC is not implemented"))
}

func (UnimplementedDuckAPIHandler) CreateLDC(context.Context, *connect.Request[api.CreateLDCRequest]) (*connect.Response[api.CreateLDCResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.CreateLDC is not implemented"))
}

func (UnimplementedDuckAPIHandler) GetLDCs(context.Context, *connect.Request[api.GetLDCsRequest]) (*connect.Response[api.GetLDCsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.GetLDCs is not implemented"))
}

func (UnimplementedDuckAPIHandler) GetLDC(context.Context, *connect.Request[api.GetLDCRequest]) (*connect.Response[api.GetLDCResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.GetLDC is not implemented"))
}

func (UnimplementedDuckAPIHandler) UpdateLDC(context.Context, *connect.Request[api.UpdateLDCRequest]) (*connect.Response[api.UpdateLDCResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.UpdateLDC is not implemented"))
}

func (UnimplementedDuckAPIHandler) DeleteLDC(context.Context, *connect.Request[api.DeleteLDCRequest]) (*connect.Response[api.DeleteLDCResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.DeleteLDC is not implemented"))
}

func (UnimplementedDuckAPIHandler) CreateEquipment(context.Context, *connect.Request[api.CreateEquipmentRequest]) (*connect.Response[api.CreateEquipmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.CreateEquipment is not implemented"))
}

func (UnimplementedDuckAPIHandler) GetEquipments(context.Context, *connect.Request[api.GetEquipmentsRequest]) (*connect.Response[api.GetEquipmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.GetEquipments is not implemented"))
}

func (UnimplementedDuckAPIHandler) GetEquipment(context.Context, *connect.Request[api.GetEquipmentRequest]) (*connect.Response[api.GetEquipmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.GetEquipment is not implemented"))
}

func (UnimplementedDuckAPIHandler) UpdateEquipment(context.Context, *connect.Request[api.UpdateEquipmentRequest]) (*connect.Response[api.UpdateEquipmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.UpdateEquipment is not implemented"))
}

func (UnimplementedDuckAPIHandler) DeleteEquipment(context.Context, *connect.Request[api.DeleteEquipmentRequest]) (*connect.Response[api.DeleteEquipmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.DeleteEquipment is not implemented"))
}

func (UnimplementedDuckAPIHandler) GetDecoderConfiguration(context.Context, *connect.Request[api.GetDecoderConfigurationRequest]) (*connect.Response[api.GetDecoderConfigurationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.GetDecoderConfiguration is not implemented"))
}

func (UnimplementedDuckAPIHandler) UpdateDecoderConfiguration(context.Context, *connect.Request[api.UpdateDecoderConfigurationRequest]) (*connect.Response[api.UpdateDecoderConfigurationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.UpdateDecoderConfiguration is not implemented"))
}

func (UnimplementedDuckAPIHandler) GetRunNumber(context.Context, *connect.Request[api.GetRunNumberRequest]) (*connect.Response[api.GetRunNumberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.GetRunNumber is not implemented"))
}

func (UnimplementedDuckAPIHandler) CheckDisabled(context.Context, *connect.Request[api.CheckDisabledRequest]) (*connect.Response[api.CheckDisabledResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.CheckDisabled is not implemented"))
}

func (UnimplementedDuckAPIHandler) GetToken(context.Context, *connect.Request[api.GetTokenRequest]) (*connect.Response[api.GetTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.GetToken is not implemented"))
}

func (UnimplementedDuckAPIHandler) StartTestDevices(context.Context, *connect.Request[api.StartTestDevicesRequest]) (*connect.Response[api.StartTestDevicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.StartTestDevices is not implemented"))
}

func (UnimplementedDuckAPIHandler) StopTestDevices(context.Context, *connect.Request[api.StopTestDevicesRequest]) (*connect.Response[api.StopTestDevicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.StopTestDevices is not implemented"))
}

func (UnimplementedDuckAPIHandler) GetTestDevicesStates(context.Context, *connect.Request[api.GetTestDevicesStatesRequest]) (*connect.Response[api.GetTestDevicesStatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.GetTestDevicesStates is not implemented"))
}

func (UnimplementedDuckAPIHandler) ListTestDevices(context.Context, *connect.Request[api.ListTestDevicesRequest]) (*connect.Response[api.ListTestDevicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.ListTestDevices is not implemented"))
}

func (UnimplementedDuckAPIHandler) GetTestDeviceStatistics(context.Context, *connect.Request[api.GetTestDeviceStatisticsRequest]) (*connect.Response[api.GetTestDeviceStatisticsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("apiService.DuckAPI.GetTestDeviceStatistics is not implemented"))
}
