// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: control.proto

package controlconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	control "github.com/jmbenlloch/next_duck/rpc/control"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RunControlName is the fully-qualified name of the RunControl service.
	RunControlName = "rpcControl.RunControl"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RunControlStartRunProcedure is the fully-qualified name of the RunControl's StartRun RPC.
	RunControlStartRunProcedure = "/rpcControl.RunControl/StartRun"
	// RunControlStopRunProcedure is the fully-qualified name of the RunControl's StopRun RPC.
	RunControlStopRunProcedure = "/rpcControl.RunControl/StopRun"
	// RunControlGetStateProcedure is the fully-qualified name of the RunControl's GetState RPC.
	RunControlGetStateProcedure = "/rpcControl.RunControl/GetState"
	// RunControlPingDevicesProcedure is the fully-qualified name of the RunControl's PingDevices RPC.
	RunControlPingDevicesProcedure = "/rpcControl.RunControl/PingDevices"
	// RunControlGetRunStatisticsProcedure is the fully-qualified name of the RunControl's
	// GetRunStatistics RPC.
	RunControlGetRunStatisticsProcedure = "/rpcControl.RunControl/GetRunStatistics"
)

// RunControlClient is a client for the rpcControl.RunControl service.
type RunControlClient interface {
	StartRun(context.Context, *connect.Request[control.DuckRequest]) (*connect.Response[control.DuckReply], error)
	StopRun(context.Context, *connect.Request[control.DuckRequest]) (*connect.Response[control.DuckReply], error)
	GetState(context.Context, *connect.Request[control.DuckRequest]) (*connect.Response[control.DuckReply], error)
	PingDevices(context.Context, *connect.Request[control.DuckRequest]) (*connect.Response[control.PingReply], error)
	GetRunStatistics(context.Context, *connect.Request[control.DuckRequest]) (*connect.Response[control.RunStatisticsReply], error)
}

// NewRunControlClient constructs a client for the rpcControl.RunControl service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRunControlClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RunControlClient {
	baseURL = strings.TrimRight(baseURL, "/")
	runControlMethods := control.File_control_proto.Services().ByName("RunControl").Methods()
	return &runControlClient{
		startRun: connect.NewClient[control.DuckRequest, control.DuckReply](
			httpClient,
			baseURL+RunControlStartRunProcedure,
			connect.WithSchema(runControlMethods.ByName("StartRun")),
			connect.WithClientOptions(opts...),
		),
		stopRun: connect.NewClient[control.DuckRequest, control.DuckReply](
			httpClient,
			baseURL+RunControlStopRunProcedure,
			connect.WithSchema(runControlMethods.ByName("StopRun")),
			connect.WithClientOptions(opts...),
		),
		getState: connect.NewClient[control.DuckRequest, control.DuckReply](
			httpClient,
			baseURL+RunControlGetStateProcedure,
			connect.WithSchema(runControlMethods.ByName("GetState")),
			connect.WithClientOptions(opts...),
		),
		pingDevices: connect.NewClient[control.DuckRequest, control.PingReply](
			httpClient,
			baseURL+RunControlPingDevicesProcedure,
			connect.WithSchema(runControlMethods.ByName("PingDevices")),
			connect.WithClientOptions(opts...),
		),
		getRunStatistics: connect.NewClient[control.DuckRequest, control.RunStatisticsReply](
			httpClient,
			baseURL+RunControlGetRunStatisticsProcedure,
			connect.WithSchema(runControlMethods.ByName("GetRunStatistics")),
			connect.WithClientOptions(opts...),
		),
	}
}

// runControlClient implements RunControlClient.
type runControlClient struct {
	startRun         *connect.Client[control.DuckRequest, control.DuckReply]
	stopRun          *connect.Client[control.DuckRequest, control.DuckReply]
	getState         *connect.Client[control.DuckRequest, control.DuckReply]
	pingDevices      *connect.Client[control.DuckRequest, control.PingReply]
	getRunStatistics *connect.Client[control.DuckRequest, control.RunStatisticsReply]
}

// StartRun calls rpcControl.RunControl.StartRun.
func (c *runControlClient) StartRun(ctx context.Context, req *connect.Request[control.DuckRequest]) (*connect.Response[control.DuckReply], error) {
	return c.startRun.CallUnary(ctx, req)
}

// StopRun calls rpcControl.RunControl.StopRun.
func (c *runControlClient) StopRun(ctx context.Context, req *connect.Request[control.DuckRequest]) (*connect.Response[control.DuckReply], error) {
	return c.stopRun.CallUnary(ctx, req)
}

// GetState calls rpcControl.RunControl.GetState.
func (c *runControlClient) GetState(ctx context.Context, req *connect.Request[control.DuckRequest]) (*connect.Response[control.DuckReply], error) {
	return c.getState.CallUnary(ctx, req)
}

// PingDevices calls rpcControl.RunControl.PingDevices.
func (c *runControlClient) PingDevices(ctx context.Context, req *connect.Request[control.DuckRequest]) (*connect.Response[control.PingReply], error) {
	return c.pingDevices.CallUnary(ctx, req)
}

// GetRunStatistics calls rpcControl.RunControl.GetRunStatistics.
func (c *runControlClient) GetRunStatistics(ctx context.Context, req *connect.Request[control.DuckRequest]) (*connect.Response[control.RunStatisticsReply], error) {
	return c.getRunStatistics.CallUnary(ctx, req)
}

// RunControlHandler is an implementation of the rpcControl.RunControl service.
type RunControlHandler interface {
	StartRun(context.Context, *connect.Request[control.DuckRequest]) (*connect.Response[control.DuckReply], error)
	StopRun(context.Context, *connect.Request[control.DuckRequest]) (*connect.Response[control.DuckReply], error)
	GetState(context.Context, *connect.Request[control.DuckRequest]) (*connect.Response[control.DuckReply], error)
	PingDevices(context.Context, *connect.Request[control.DuckRequest]) (*connect.Response[control.PingReply], error)
	GetRunStatistics(context.Context, *connect.Request[control.DuckRequest]) (*connect.Response[control.RunStatisticsReply], error)
}

// NewRunControlHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRunControlHandler(svc RunControlHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	runControlMethods := control.File_control_proto.Services().ByName("RunControl").Methods()
	runControlStartRunHandler := connect.NewUnaryHandler(
		RunControlStartRunProcedure,
		svc.StartRun,
		connect.WithSchema(runControlMethods.ByName("StartRun")),
		connect.WithHandlerOptions(opts...),
	)
	runControlStopRunHandler := connect.NewUnaryHandler(
		RunControlStopRunProcedure,
		svc.StopRun,
		connect.WithSchema(runControlMethods.ByName("StopRun")),
		connect.WithHandlerOptions(opts...),
	)
	runControlGetStateHandler := connect.NewUnaryHandler(
		RunControlGetStateProcedure,
		svc.GetState,
		connect.WithSchema(runControlMethods.ByName("GetState")),
		connect.WithHandlerOptions(opts...),
	)
	runControlPingDevicesHandler := connect.NewUnaryHandler(
		RunControlPingDevicesProcedure,
		svc.PingDevices,
		connect.WithSchema(runControlMethods.ByName("PingDevices")),
		connect.WithHandlerOptions(opts...),
	)
	runControlGetRunStatisticsHandler := connect.NewUnaryHandler(
		RunControlGetRunStatisticsProcedure,
		svc.GetRunStatistics,
		connect.WithSchema(runControlMethods.ByName("GetRunStatistics")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rpcControl.RunControl/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RunControlStartRunProcedure:
			runControlStartRunHandler.ServeHTTP(w, r)
		case RunControlStopRunProcedure:
			runControlStopRunHandler.ServeHTTP(w, r)
		case RunControlGetStateProcedure:
			runControlGetStateHandler.ServeHTTP(w, r)
		case RunControlPingDevicesProcedure:
			runControlPingDevicesHandler.ServeHTTP(w, r)
		case RunControlGetRunStatisticsProcedure:
			runControlGetRunStatisticsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRunControlHandler returns CodeUnimplemented from all methods.
type UnimplementedRunControlHandler struct{}

func (UnimplementedRunControlHandler) StartRun(context.Context, *connect.Request[control.DuckRequest]) (*connect.Response[control.DuckReply], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpcControl.RunControl.StartRun is not implemented"))
}

func (UnimplementedRunControlHandler) StopRun(context.Context, *connect.Request[control.DuckRequest]) (*connect.Response[control.DuckReply], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpcControl.RunControl.StopRun is not implemented"))
}

func (UnimplementedRunControlHandler) GetState(context.Context, *connect.Request[control.DuckRequest]) (*connect.Response[control.DuckReply], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpcControl.RunControl.GetState is not implemented"))
}

func (UnimplementedRunControlHandler) PingDevices(context.Context, *connect.Request[control.DuckRequest]) (*connect.Response[control.PingReply], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpcControl.RunControl.PingDevices is not implemented"))
}

func (UnimplementedRunControlHandler) GetRunStatistics(context.Context, *connect.Request[control.DuckRequest]) (*connect.Response[control.RunStatisticsReply], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpcControl.RunControl.GetRunStatistics is not implemented"))
}
