// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	database "github.com/jmbenlloch/next_duck/pkg/database"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

// CreateEquipment provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateEquipment(ctx context.Context, arg database.CreateEquipmentParams) (sql.Result, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateEquipment")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateEquipmentParams) (sql.Result, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateEquipmentParams) sql.Result); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.CreateEquipmentParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateGDC provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateGDC(ctx context.Context, arg database.CreateGDCParams) (sql.Result, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateGDC")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateGDCParams) (sql.Result, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateGDCParams) sql.Result); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.CreateGDCParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateLDC provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateLDC(ctx context.Context, arg database.CreateLDCParams) (sql.Result, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateLDC")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateLDCParams) (sql.Result, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateLDCParams) sql.Result); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.CreateLDCParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateSimulatorParams provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateSimulatorParams(ctx context.Context, arg database.CreateSimulatorParamsParams) (sql.Result, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSimulatorParams")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateSimulatorParamsParams) (sql.Result, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateSimulatorParamsParams) sql.Result); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.CreateSimulatorParamsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEquipment provides a mock function with given fields: ctx, id
func (_m *Querier) DeleteEquipment(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEquipment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteGDC provides a mock function with given fields: ctx, id
func (_m *Querier) DeleteGDC(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGDC")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteLDC provides a mock function with given fields: ctx, id
func (_m *Querier) DeleteLDC(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLDC")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSimulatorParams provides a mock function with given fields: ctx, equipmentid
func (_m *Querier) DeleteSimulatorParams(ctx context.Context, equipmentid int32) error {
	ret := _m.Called(ctx, equipmentid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSimulatorParams")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, equipmentid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDecoderParams provides a mock function with given fields: ctx
func (_m *Querier) GetDecoderParams(ctx context.Context) (database.Decoderparam, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDecoderParams")
	}

	var r0 database.Decoderparam
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (database.Decoderparam, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) database.Decoderparam); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(database.Decoderparam)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDisabledEquipments provides a mock function with given fields: ctx
func (_m *Querier) GetDisabledEquipments(ctx context.Context) ([]database.Equipment, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDisabledEquipments")
	}

	var r0 []database.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]database.Equipment, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []database.Equipment); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDisabledGDCs provides a mock function with given fields: ctx
func (_m *Querier) GetDisabledGDCs(ctx context.Context) ([]database.Gdc, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDisabledGDCs")
	}

	var r0 []database.Gdc
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]database.Gdc, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []database.Gdc); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Gdc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDisabledLDCs provides a mock function with given fields: ctx
func (_m *Querier) GetDisabledLDCs(ctx context.Context) ([]database.Ldc, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDisabledLDCs")
	}

	var r0 []database.Ldc
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]database.Ldc, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []database.Ldc); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Ldc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDuckParams provides a mock function with given fields: ctx
func (_m *Querier) GetDuckParams(ctx context.Context) (database.Duckparam, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDuckParams")
	}

	var r0 database.Duckparam
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (database.Duckparam, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) database.Duckparam); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(database.Duckparam)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEquipment provides a mock function with given fields: ctx, id
func (_m *Querier) GetEquipment(ctx context.Context, id int32) (database.Equipment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEquipment")
	}

	var r0 database.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (database.Equipment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) database.Equipment); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(database.Equipment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGDC provides a mock function with given fields: ctx, id
func (_m *Querier) GetGDC(ctx context.Context, id int32) (database.Gdc, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetGDC")
	}

	var r0 database.Gdc
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (database.Gdc, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) database.Gdc); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(database.Gdc)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGDCsWithoutWrite provides a mock function with given fields: ctx
func (_m *Querier) GetGDCsWithoutWrite(ctx context.Context) ([]database.Gdc, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGDCsWithoutWrite")
	}

	var r0 []database.Gdc
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]database.Gdc, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []database.Gdc); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Gdc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLDC provides a mock function with given fields: ctx, id
func (_m *Querier) GetLDC(ctx context.Context, id int32) (database.Ldc, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLDC")
	}

	var r0 database.Ldc
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (database.Ldc, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) database.Ldc); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(database.Ldc)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestRun provides a mock function with given fields: ctx
func (_m *Querier) GetLatestRun(ctx context.Context) (int32, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestRun")
	}

	var r0 int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int32, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int32); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestRunWithTimestamp provides a mock function with given fields: ctx
func (_m *Querier) GetLatestRunWithTimestamp(ctx context.Context) (database.Run, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestRunWithTimestamp")
	}

	var r0 database.Run
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (database.Run, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) database.Run); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(database.Run)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRateByRun provides a mock function with given fields: ctx, run
func (_m *Querier) GetRateByRun(ctx context.Context, run int32) (int32, error) {
	ret := _m.Called(ctx, run)

	if len(ret) == 0 {
		panic("no return value specified for GetRateByRun")
	}

	var r0 int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (int32, error)); ok {
		return rf(ctx, run)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) int32); ok {
		r0 = rf(ctx, run)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, run)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSimulatorParams provides a mock function with given fields: ctx, equipmentid
func (_m *Querier) GetSimulatorParams(ctx context.Context, equipmentid int32) (database.Simulatorparam, error) {
	ret := _m.Called(ctx, equipmentid)

	if len(ret) == 0 {
		panic("no return value specified for GetSimulatorParams")
	}

	var r0 database.Simulatorparam
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (database.Simulatorparam, error)); ok {
		return rf(ctx, equipmentid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) database.Simulatorparam); ok {
		r0 = rf(ctx, equipmentid)
	} else {
		r0 = ret.Get(0).(database.Simulatorparam)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, equipmentid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTestDeviceParams provides a mock function with given fields: ctx
func (_m *Querier) GetTestDeviceParams(ctx context.Context) ([]database.Testdeviceparam, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTestDeviceParams")
	}

	var r0 []database.Testdeviceparam
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]database.Testdeviceparam, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []database.Testdeviceparam); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Testdeviceparam)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertGDCBytes provides a mock function with given fields: ctx, arg
func (_m *Querier) InsertGDCBytes(ctx context.Context, arg database.InsertGDCBytesParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertGDCBytes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.InsertGDCBytesParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertGDCErrorCount provides a mock function with given fields: ctx, arg
func (_m *Querier) InsertGDCErrorCount(ctx context.Context, arg database.InsertGDCErrorCountParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertGDCErrorCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.InsertGDCErrorCountParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertGDCEvents provides a mock function with given fields: ctx, arg
func (_m *Querier) InsertGDCEvents(ctx context.Context, arg database.InsertGDCEventsParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertGDCEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.InsertGDCEventsParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertLDCBytes provides a mock function with given fields: ctx, arg
func (_m *Querier) InsertLDCBytes(ctx context.Context, arg database.InsertLDCBytesParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertLDCBytes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.InsertLDCBytesParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertLDCErrorCount provides a mock function with given fields: ctx, arg
func (_m *Querier) InsertLDCErrorCount(ctx context.Context, arg database.InsertLDCErrorCountParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertLDCErrorCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.InsertLDCErrorCountParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertLDCEvents provides a mock function with given fields: ctx, arg
func (_m *Querier) InsertLDCEvents(ctx context.Context, arg database.InsertLDCEventsParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertLDCEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.InsertLDCEventsParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertNewRun provides a mock function with given fields: ctx
func (_m *Querier) InsertNewRun(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InsertNewRun")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertRate provides a mock function with given fields: ctx, arg
func (_m *Querier) InsertRate(ctx context.Context, arg database.InsertRateParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertRate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.InsertRateParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListEquipments provides a mock function with given fields: ctx
func (_m *Querier) ListEquipments(ctx context.Context) ([]database.Equipment, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListEquipments")
	}

	var r0 []database.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]database.Equipment, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []database.Equipment); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListGDCs provides a mock function with given fields: ctx
func (_m *Querier) ListGDCs(ctx context.Context) ([]database.Gdc, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListGDCs")
	}

	var r0 []database.Gdc
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]database.Gdc, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []database.Gdc); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Gdc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListLDCs provides a mock function with given fields: ctx
func (_m *Querier) ListLDCs(ctx context.Context) ([]database.Ldc, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListLDCs")
	}

	var r0 []database.Ldc
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]database.Ldc, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []database.Ldc); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Ldc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSimulatorParams provides a mock function with given fields: ctx
func (_m *Querier) ListSimulatorParams(ctx context.Context) ([]database.Simulatorparam, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSimulatorParams")
	}

	var r0 []database.Simulatorparam
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]database.Simulatorparam, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []database.Simulatorparam); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Simulatorparam)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TruncateDecoderParams provides a mock function with given fields: ctx
func (_m *Querier) TruncateDecoderParams(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TruncateDecoderParams")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDecoderParams provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateDecoderParams(ctx context.Context, arg database.UpdateDecoderParamsParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDecoderParams")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateDecoderParamsParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateEquipment provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateEquipment(ctx context.Context, arg database.UpdateEquipmentParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEquipment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateEquipmentParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateGDC provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateGDC(ctx context.Context, arg database.UpdateGDCParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGDC")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateGDCParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLDC provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateLDC(ctx context.Context, arg database.UpdateLDCParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLDC")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateLDCParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRate provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateRate(ctx context.Context, arg database.UpdateRateParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateRateParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRunStartTime provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateRunStartTime(ctx context.Context, arg database.UpdateRunStartTimeParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRunStartTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateRunStartTimeParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRunStopTime provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateRunStopTime(ctx context.Context, arg database.UpdateRunStopTimeParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRunStopTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateRunStopTimeParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSimulatorParams provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateSimulatorParams(ctx context.Context, arg database.UpdateSimulatorParamsParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSimulatorParams")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateSimulatorParamsParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
